#ifndef MIDIPLAN_DEVICES_GM_DEVICE_H
#define MIDIPLAN_DEVICES_GM_DEVICE_H

#include <midiplan/device.h>

extern const midiplan_device_t gm_device;

#define GM_PROGRAM_ACOUSTIC_GRAND_PIANO  (0x00) // 1   
#define GM_PROGRAM_BRIGHT_ACOUSTIC_PIANO (0x01) // 2   
#define GM_PROGRAM_ELECTRIC_GRAND_PIANO  (0x02) // 3   
#define GM_PROGRAM_HONKY_TONK_PIANO      (0x03) // 4   
#define GM_PROGRAM_ELECTRIC_PIANO_1      (0x04) // 5   
#define GM_PROGRAM_ELECTRIC_PIANO_2      (0x05) // 6   
#define GM_PROGRAM_HARPSICHORD           (0x06) // 7   
#define GM_PROGRAM_CLAVI                 (0x07) // 8   
#define GM_PROGRAM_CELESTA               (0x08) // 9   
#define GM_PROGRAM_GLOCKENSPIEL          (0x09) // 10  
#define GM_PROGRAM_MUSIC_BOX             (0x0A) // 11  
#define GM_PROGRAM_VIBRAPHONE            (0x0B) // 12  
#define GM_PROGRAM_MARIMBA               (0x0C) // 13  
#define GM_PROGRAM_XYLOPHONE             (0x0D) // 14  
#define GM_PROGRAM_TUBULAR_BELLS         (0x0E) // 15  
#define GM_PROGRAM_DULCIMER              (0x0F) // 16  
#define GM_PROGRAM_DRAWBAR_ORGAN         (0x10) // 17  
#define GM_PROGRAM_PERCUSSIVE_ORGAN      (0x11) // 18  
#define GM_PROGRAM_ROCK_ORGAN            (0x12) // 19  
#define GM_PROGRAM_CHURCH_ORGAN          (0x13) // 20  
#define GM_PROGRAM_REED_ORGAN            (0x14) // 21  
#define GM_PROGRAM_ACCORDION             (0x15) // 22  
#define GM_PROGRAM_HARMONICA             (0x16) // 23  
#define GM_PROGRAM_TANGO_ACCORDION       (0x17) // 24  
#define GM_PROGRAM_ACOUSTIC_GUITAR_NYLON (0x18) // 25  
#define GM_PROGRAM_ACOUSTIC_GUITAR_STEEL (0x19) // 26  
#define GM_PROGRAM_ELECTRIC_GUITAR_JAZZ  (0x1A) // 27  
#define GM_PROGRAM_ELECTRIC_GUITAR_CLEAN (0x1B) // 28  
#define GM_PROGRAM_ELECTRIC_GUITAR_MUTED (0x1C) // 29  
#define GM_PROGRAM_OVERDRIVEN_GUITAR     (0x1D) // 30  
#define GM_PROGRAM_DISTORTION_GUITAR     (0x1E) // 31  
#define GM_PROGRAM_GUITAR_HARMONICS      (0x1F) // 32  
#define GM_PROGRAM_ACOUSTIC_BASS         (0x20) // 33  
#define GM_PROGRAM_ELECTRIC_BASS_FINGER  (0x21) // 34  
#define GM_PROGRAM_ELECTRIC_BASS_PICK    (0x22) // 35  
#define GM_PROGRAM_FRETLESS_BASS         (0x23) // 36  
#define GM_PROGRAM_SLAP_BASS_1           (0x24) // 37  
#define GM_PROGRAM_SLAP_BASS_2           (0x25) // 38  
#define GM_PROGRAM_SYNTH_BASS_1          (0x26) // 39  
#define GM_PROGRAM_SYNTH_BASS_2          (0x27) // 40  
#define GM_PROGRAM_VIOLIN                (0x28) // 41  
#define GM_PROGRAM_VIOLA                 (0x29) // 42  
#define GM_PROGRAM_CELLO                 (0x2A) // 43  
#define GM_PROGRAM_CONTRABASS            (0x2B) // 44  
#define GM_PROGRAM_TREMOLO_STRINGS       (0x2C) // 45  
#define GM_PROGRAM_PIZZICATO_STRINGS     (0x2D) // 46  
#define GM_PROGRAM_ORCHESTRAL_HARP       (0x2E) // 47  
#define GM_PROGRAM_TIMPANI               (0x2F) // 48  
#define GM_PROGRAM_STRING_ENSEMBLE_1     (0x30) // 49  
#define GM_PROGRAM_STRING_ENSEMBLE_2     (0x31) // 50  
#define GM_PROGRAM_SYNTHSTRINGS_1        (0x32) // 51  
#define GM_PROGRAM_SYNTHSTRINGS_2        (0x33) // 52  
#define GM_PROGRAM_CHOIR_AAHS            (0x34) // 53  
#define GM_PROGRAM_VOICE_OOHS            (0x35) // 54  
#define GM_PROGRAM_SYNTH_VOICE           (0x36) // 55  
#define GM_PROGRAM_ORCHESTRA_HIT         (0x37) // 56  
#define GM_PROGRAM_TRUMPET               (0x38) // 57  
#define GM_PROGRAM_TROMBONE              (0x39) // 58  
#define GM_PROGRAM_TUBA                  (0x3A) // 59  
#define GM_PROGRAM_MUTED_TRUMPET         (0x3B) // 60  
#define GM_PROGRAM_FRENCH_HORN           (0x3C) // 61  
#define GM_PROGRAM_BRASS_SECTION         (0x3D) // 62  
#define GM_PROGRAM_SYNTHBRASS_1          (0x3E) // 63  
#define GM_PROGRAM_SYNTHBRASS_2          (0x3F) // 64  
#define GM_PROGRAM_SOPRANO_SAX           (0x40) // 65  
#define GM_PROGRAM_ALTO_SAX              (0x41) // 66  
#define GM_PROGRAM_TENOR_SAX             (0x42) // 67  
#define GM_PROGRAM_BARITONE_SAX          (0x43) // 68  
#define GM_PROGRAM_OBOE                  (0x44) // 69  
#define GM_PROGRAM_ENGLISH_HORN          (0x45) // 70  
#define GM_PROGRAM_BASSOON               (0x46) // 71  
#define GM_PROGRAM_CLARINET              (0x47) // 72  
#define GM_PROGRAM_PICCOLO               (0x48) // 73  
#define GM_PROGRAM_FLUTE                 (0x49) // 74  
#define GM_PROGRAM_RECORDER              (0x4A) // 75  
#define GM_PROGRAM_PAN_FLUTE             (0x4B) // 76  
#define GM_PROGRAM_BLOWN_BOTTLE          (0x4C) // 77  
#define GM_PROGRAM_SHAKUHACHI            (0x4D) // 78  
#define GM_PROGRAM_WHISTLE               (0x4E) // 79  
#define GM_PROGRAM_OCARINA               (0x4F) // 80  
#define GM_PROGRAM_LEAD_1_SQUARE         (0x50) // 81  
#define GM_PROGRAM_LEAD_2_SAWTOOTH       (0x51) // 82  
#define GM_PROGRAM_LEAD_3_CALLIOPE       (0x52) // 83  
#define GM_PROGRAM_LEAD_4_CHIFF          (0x53) // 84  
#define GM_PROGRAM_LEAD_5_CHARANG        (0x54) // 85  
#define GM_PROGRAM_LEAD_6_VOICE          (0x55) // 86  
#define GM_PROGRAM_LEAD_7_FIFTHS         (0x56) // 87  
#define GM_PROGRAM_LEAD_8_BASS_LEAD      (0x57) // 88  
#define GM_PROGRAM_PAD_1_NEW_AGE         (0x58) // 89  
#define GM_PROGRAM_PAD_2_WARM            (0x59) // 90  
#define GM_PROGRAM_PAD_3_POLYSYNTH       (0x5A) // 91  
#define GM_PROGRAM_PAD_4_CHOIR           (0x5B) // 92  
#define GM_PROGRAM_PAD_5_BOWED           (0x5C) // 93  
#define GM_PROGRAM_PAD_6_METALLIC        (0x5D) // 94  
#define GM_PROGRAM_PAD_7_HALO            (0x5E) // 95  
#define GM_PROGRAM_PAD_8_SWEEP           (0x5F) // 96  
#define GM_PROGRAM_FX_1_RAIN             (0x60) // 97  
#define GM_PROGRAM_FX_2_SOUNDTRACK       (0x61) // 98  
#define GM_PROGRAM_FX_3_CRYSTAL          (0x62) // 99  
#define GM_PROGRAM_FX_4_ATMOSPHERE       (0x63) // 100 
#define GM_PROGRAM_FX_5_BRIGHTNESS       (0x64) // 101 
#define GM_PROGRAM_FX_6_GOBLINS          (0x65) // 102 
#define GM_PROGRAM_FX_7_ECHOES           (0x66) // 103 
#define GM_PROGRAM_FX_8_SCI_FI           (0x67) // 104 
#define GM_PROGRAM_SITAR                 (0x68) // 105 
#define GM_PROGRAM_BANJO                 (0x69) // 106 
#define GM_PROGRAM_SHAMISEN              (0x6A) // 107 
#define GM_PROGRAM_KOTO                  (0x6B) // 108 
#define GM_PROGRAM_KALIMBA               (0x6C) // 109 
#define GM_PROGRAM_BAG_PIPE              (0x6D) // 110 
#define GM_PROGRAM_FIDDLE                (0x6E) // 111 
#define GM_PROGRAM_SHANAI                (0x6F) // 112 
#define GM_PROGRAM_TINKLE_BELL           (0x70) // 113 
#define GM_PROGRAM_AGOGO                 (0x71) // 114 
#define GM_PROGRAM_STEEL_DRUMS           (0x72) // 115 
#define GM_PROGRAM_WOODBLOCK             (0x73) // 116 
#define GM_PROGRAM_TAIKO_DRUM            (0x74) // 117 
#define GM_PROGRAM_MELODIC_TOM           (0x75) // 118 
#define GM_PROGRAM_SYNTH_DRUM            (0x76) // 119 
#define GM_PROGRAM_REVERSE_CYMBAL        (0x77) // 120 
#define GM_PROGRAM_GUITAR_FRET_NOISE     (0x78) // 121 
#define GM_PROGRAM_BREATH_NOISE          (0x79) // 122 
#define GM_PROGRAM_SEASHORE              (0x7A) // 123 
#define GM_PROGRAM_BIRD_TWEET            (0x7B) // 124 
#define GM_PROGRAM_TELEPHONE_RING        (0x7C) // 125 
#define GM_PROGRAM_HELICOPTER            (0x7D) // 126 
#define GM_PROGRAM_APPLAUSE              (0x7E) // 127 
#define GM_PROGRAM_GUNSHOT               (0x7F) // 128 

#define GM_RANGE_INVALID                 (0x00)
#define GM_RANGE_DEFAULT                 (0x0F)

#define GM_PERCUSSION_UNDEFINED_00       (0x00) // 1  
#define GM_PERCUSSION_UNDEFINED_01       (0x01) // 2  
#define GM_PERCUSSION_UNDEFINED_02       (0x02) // 3  
#define GM_PERCUSSION_UNDEFINED_03       (0x03) // 4  
#define GM_PERCUSSION_UNDEFINED_04       (0x04) // 5  
#define GM_PERCUSSION_UNDEFINED_05       (0x05) // 6  
#define GM_PERCUSSION_UNDEFINED_06       (0x06) // 7  
#define GM_PERCUSSION_UNDEFINED_07       (0x07) // 8  
#define GM_PERCUSSION_UNDEFINED_08       (0x08) // 9  
#define GM_PERCUSSION_UNDEFINED_09       (0x09) // 10 
#define GM_PERCUSSION_UNDEFINED_0A       (0x0A) // 11 
#define GM_PERCUSSION_UNDEFINED_0B       (0x0B) // 12 
#define GM_PERCUSSION_UNDEFINED_0C       (0x0C) // 13 
#define GM_PERCUSSION_UNDEFINED_0D       (0x0D) // 14 
#define GM_PERCUSSION_UNDEFINED_0E       (0x0E) // 15 
#define GM_PERCUSSION_UNDEFINED_0F       (0x0F) // 16 
#define GM_PERCUSSION_UNDEFINED_10       (0x10) // 17 
#define GM_PERCUSSION_UNDEFINED_11       (0x11) // 18 
#define GM_PERCUSSION_UNDEFINED_12       (0x12) // 19 
#define GM_PERCUSSION_UNDEFINED_13       (0x13) // 20 
#define GM_PERCUSSION_UNDEFINED_14       (0x14) // 21 
#define GM_PERCUSSION_UNDEFINED_15       (0x15) // 22 
#define GM_PERCUSSION_UNDEFINED_16       (0x16) // 23 
#define GM_PERCUSSION_UNDEFINED_17       (0x17) // 24 
#define GM_PERCUSSION_UNDEFINED_18       (0x18) // 25 
#define GM_PERCUSSION_UNDEFINED_19       (0x19) // 26 
#define GM_PERCUSSION_UNDEFINED_1A       (0x1A) // 27 
#define GM_PERCUSSION_UNDEFINED_1B       (0x1B) // 28 
#define GM_PERCUSSION_UNDEFINED_1C       (0x1C) // 29 
#define GM_PERCUSSION_UNDEFINED_1D       (0x1D) // 30 
#define GM_PERCUSSION_UNDEFINED_1E       (0x1E) // 31 
#define GM_PERCUSSION_UNDEFINED_1F       (0x1F) // 32 
#define GM_PERCUSSION_UNDEFINED_20       (0x20) // 33 
#define GM_PERCUSSION_UNDEFINED_21       (0x21) // 34 
#define GM_PERCUSSION_UNDEFINED_22       (0x22) // 35 
#define GM_PERCUSSION_ACOUSTIC_BASS_DRUM (0x23) // 36 
#define GM_PERCUSSION_BASS_DRUM_1        (0x24) // 37 
#define GM_PERCUSSION_SIDE_STICK         (0x25) // 38 
#define GM_PERCUSSION_ACOUSTIC_SNARE     (0x26) // 39 
#define GM_PERCUSSION_HAND_CLAP          (0x27) // 40 
#define GM_PERCUSSION_ELECTRIC_SNARE     (0x28) // 41 
#define GM_PERCUSSION_LOW_FLOOR_TOM      (0x29) // 42 
#define GM_PERCUSSION_CLOSED_HI_HAT      (0x2A) // 43 
#define GM_PERCUSSION_HIGH_FLOOR_TOM     (0x2B) // 44 
#define GM_PERCUSSION_PEDAL_HI_HAT       (0x2C) // 45 
#define GM_PERCUSSION_LOW_TOM            (0x2D) // 46 
#define GM_PERCUSSION_OPEN_HI_HAT        (0x2E) // 47 
#define GM_PERCUSSION_LOW_MID_TOM        (0x2F) // 48 
#define GM_PERCUSSION_HI_MID_TOM         (0x30) // 49 
#define GM_PERCUSSION_CRASH_CYMBAL_1     (0x31) // 50 
#define GM_PERCUSSION_HIGH_TOM           (0x32) // 51 
#define GM_PERCUSSION_RIDE_CYMBAL_1      (0x33) // 52 
#define GM_PERCUSSION_CHINESE_CYMBAL     (0x34) // 53 
#define GM_PERCUSSION_RIDE_BELL          (0x35) // 54 
#define GM_PERCUSSION_TAMBOURINE         (0x36) // 55 
#define GM_PERCUSSION_SPLASH_CYMBAL      (0x37) // 56 
#define GM_PERCUSSION_COWBELL            (0x38) // 57 
#define GM_PERCUSSION_CRASH_CYMBAL_2     (0x39) // 58 
#define GM_PERCUSSION_VIBRASLAP          (0x3A) // 59 
#define GM_PERCUSSION_RIDE_CYMBAL_2      (0x3B) // 60 
#define GM_PERCUSSION_HI_BONGO           (0x3C) // 61 
#define GM_PERCUSSION_LOW_BONGO          (0x3D) // 62 
#define GM_PERCUSSION_MUTE_HI_CONGA      (0x3E) // 63 
#define GM_PERCUSSION_OPEN_HI_CONGA      (0x3F) // 64 
#define GM_PERCUSSION_LOW_CONGA          (0x40) // 65 
#define GM_PERCUSSION_HIGH_TIMBALE       (0x41) // 66 
#define GM_PERCUSSION_LOW_TIMBALE        (0x42) // 67 
#define GM_PERCUSSION_HIGH_AGOGO         (0x43) // 68 
#define GM_PERCUSSION_LOW_AGOGO          (0x44) // 69 
#define GM_PERCUSSION_CABASA             (0x45) // 70 
#define GM_PERCUSSION_MARACAS            (0x46) // 71 
#define GM_PERCUSSION_SHORT_WHISTLE      (0x47) // 72 
#define GM_PERCUSSION_LONG_WHISTLE       (0x48) // 73 
#define GM_PERCUSSION_SHORT_GUIRO        (0x49) // 74 
#define GM_PERCUSSION_LONG_GUIRO         (0x4A) // 75 
#define GM_PERCUSSION_CLAVES             (0x4B) // 76 
#define GM_PERCUSSION_HI_WOOD_BLOCK      (0x4C) // 77 
#define GM_PERCUSSION_LOW_WOOD_BLOCK     (0x4D) // 78 
#define GM_PERCUSSION_MUTE_CUICA         (0x4E) // 79 
#define GM_PERCUSSION_OPEN_CUICA         (0x4F) // 80 
#define GM_PERCUSSION_MUTE_TRIANGLE      (0x50) // 81 
#define GM_PERCUSSION_OPEN_TRIANGLE      (0x51) // 82 
#define GM_PERCUSSION_UNDEFINED_52       (0x52) // 83 
#define GM_PERCUSSION_UNDEFINED_53       (0x53) // 84 
#define GM_PERCUSSION_UNDEFINED_54       (0x54) // 85 
#define GM_PERCUSSION_UNDEFINED_55       (0x55) // 86 
#define GM_PERCUSSION_UNDEFINED_56       (0x56) // 87 
#define GM_PERCUSSION_UNDEFINED_57       (0x57) // 88 
#define GM_PERCUSSION_UNDEFINED_58       (0x58) // 89 
#define GM_PERCUSSION_UNDEFINED_59       (0x59) // 90 
#define GM_PERCUSSION_UNDEFINED_5A       (0x5A) // 91 
#define GM_PERCUSSION_UNDEFINED_5B       (0x5B) // 92 
#define GM_PERCUSSION_UNDEFINED_5C       (0x5C) // 93 
#define GM_PERCUSSION_UNDEFINED_5D       (0x5D) // 94 
#define GM_PERCUSSION_UNDEFINED_5E       (0x5E) // 95 
#define GM_PERCUSSION_UNDEFINED_5F       (0x5F) // 96 
#define GM_PERCUSSION_UNDEFINED_60       (0x60) // 97 
#define GM_PERCUSSION_UNDEFINED_61       (0x61) // 98 
#define GM_PERCUSSION_UNDEFINED_62       (0x62) // 99 
#define GM_PERCUSSION_UNDEFINED_63       (0x63) // 100
#define GM_PERCUSSION_UNDEFINED_64       (0x64) // 101
#define GM_PERCUSSION_UNDEFINED_65       (0x65) // 102
#define GM_PERCUSSION_UNDEFINED_66       (0x66) // 103
#define GM_PERCUSSION_UNDEFINED_67       (0x67) // 104
#define GM_PERCUSSION_UNDEFINED_68       (0x68) // 105
#define GM_PERCUSSION_UNDEFINED_69       (0x69) // 106
#define GM_PERCUSSION_UNDEFINED_6A       (0x6A) // 107
#define GM_PERCUSSION_UNDEFINED_6B       (0x6B) // 108
#define GM_PERCUSSION_UNDEFINED_6C       (0x6C) // 109
#define GM_PERCUSSION_UNDEFINED_6D       (0x6D) // 110
#define GM_PERCUSSION_UNDEFINED_6E       (0x6E) // 111
#define GM_PERCUSSION_UNDEFINED_6F       (0x6F) // 112
#define GM_PERCUSSION_UNDEFINED_70       (0x70) // 113
#define GM_PERCUSSION_UNDEFINED_71       (0x71) // 114
#define GM_PERCUSSION_UNDEFINED_72       (0x72) // 115
#define GM_PERCUSSION_UNDEFINED_73       (0x73) // 116
#define GM_PERCUSSION_UNDEFINED_74       (0x74) // 117
#define GM_PERCUSSION_UNDEFINED_75       (0x75) // 118
#define GM_PERCUSSION_UNDEFINED_76       (0x76) // 119
#define GM_PERCUSSION_UNDEFINED_77       (0x77) // 120
#define GM_PERCUSSION_UNDEFINED_78       (0x78) // 121
#define GM_PERCUSSION_UNDEFINED_79       (0x79) // 122
#define GM_PERCUSSION_UNDEFINED_7A       (0x7A) // 123
#define GM_PERCUSSION_UNDEFINED_7B       (0x7B) // 124
#define GM_PERCUSSION_UNDEFINED_7C       (0x7C) // 125
#define GM_PERCUSSION_UNDEFINED_7D       (0x7D) // 126
#define GM_PERCUSSION_UNDEFINED_7E       (0x7E) // 127
#define GM_PERCUSSION_UNDEFINED_7F       (0x7F) // 128

#endif
