#ifndef MIDIPLAN_DEVICES_KAWAI_PHM_H
#define MIDIPLAN_DEVICES_KAWAI_PHM_H

#include <midiplan/device.h>

extern const midiplan_device_t kawai_phm;

#define KAWAI_PHM_LOWEST_NOTE  (  0)
#define KAWAI_PHM_MIDDLE_C     ( 60)
#define KAWAI_PHM_HIGHEST_NOTE (127)

#define KAWAI_PHM_PROGRAM_UP_PIANO                 (  0)
#define KAWAI_PHM_PROGRAM_JAZZPIANO                (  1)
#define KAWAI_PHM_PROGRAM_HONKY_TONK               (  2)
#define KAWAI_PHM_PROGRAM_REAL_RODES               (  3)
#define KAWAI_PHM_PROGRAM_ELECTRIC_PIANO           (  4)
#define KAWAI_PHM_PROGRAM_ELECTRIC_GRAND_PIANO_1   (  5)
#define KAWAI_PHM_PROGRAM_FX_PIANO                 (  6)
#define KAWAI_PHM_PROGRAM_BASS_GUITAR_1            (  7)
#define KAWAI_PHM_PROGRAM_CONTRABASS               (  8)
#define KAWAI_PHM_PROGRAM_DA_BASS                  (  9)
#define KAWAI_PHM_PROGRAM_KICK_BASS_1              ( 10)
#define KAWAI_PHM_PROGRAM_PULL_BASS                ( 11)
#define KAWAI_PHM_PROGRAM_ANALOG_BRASS_1           ( 12)
#define KAWAI_PHM_PROGRAM_BRASS_ENSEMBLE_1         ( 13)
#define KAWAI_PHM_PROGRAM_BRASS_ENSEMBLE_2         ( 14)
#define KAWAI_PHM_PROGRAM_SOFT_BRASS               ( 15)
#define KAWAI_PHM_PROGRAM_SYNTH_BRASS              ( 16)
#define KAWAI_PHM_PROGRAM_NASTY_BRASS              ( 17)
#define KAWAI_PHM_PROGRAM_ACOUSTIC_GUITAR          ( 18)
#define KAWAI_PHM_PROGRAM_DISTORTED_GUITAR         ( 19)
#define KAWAI_PHM_PROGRAM_STRATTO                  ( 20)
#define KAWAI_PHM_PROGRAM_HARMONICS                ( 21)
#define KAWAI_PHM_PROGRAM_REPEATER                 ( 22)
#define KAWAI_PHM_PROGRAM_BANJO                    ( 23)
#define KAWAI_PHM_PROGRAM_PHANTOM                  ( 24)
#define KAWAI_PHM_PROGRAM_OVERDRIVE                ( 25)
#define KAWAI_PHM_PROGRAM_BREATH_ORG               ( 26)
#define KAWAI_PHM_PROGRAM_DEEP_PURPLE              ( 27)
#define KAWAI_PHM_PROGRAM_SACRE_COEUR              ( 28)
#define KAWAI_PHM_PROGRAM_CASTLE_STRINGS           ( 29)
#define KAWAI_PHM_PROGRAM_FAT_STRINGS              ( 30)
#define KAWAI_PHM_PROGRAM_GRAND_STRINGS            ( 31)
#define KAWAI_PHM_PROGRAM_LINE_STRINGS             ( 32)
#define KAWAI_PHM_PROGRAM_STRING_PAD               ( 33)
#define KAWAI_PHM_PROGRAM_ROSIN_PUNCH              ( 34)
#define KAWAI_PHM_PROGRAM_VELO_STRING              ( 35)
#define KAWAI_PHM_PROGRAM_BACKIN_SY_1              ( 36)
#define KAWAI_PHM_PROGRAM_SYNTH_SOLO_1             ( 37)
#define KAWAI_PHM_PROGRAM_HELLO                    ( 38)
#define KAWAI_PHM_PROGRAM_JUMP_PHM                 ( 39)
#define KAWAI_PHM_PROGRAM_SQUARE_LEAD              ( 40)
#define KAWAI_PHM_PROGRAM_SOLOIST                  ( 41)
#define KAWAI_PHM_PROGRAM_ANALOG_SYNTH             ( 42)
#define KAWAI_PHM_PROGRAM_REVERB_SYNTH             ( 43)
#define KAWAI_PHM_PROGRAM_HALLOWEEN                ( 44)
#define KAWAI_PHM_PROGRAM_WATER_DRAMA              ( 45)
#define KAWAI_PHM_PROGRAM_DEEP_SPACE               ( 46)
#define KAWAI_PHM_PROGRAM_MACHINE                  ( 47)
#define KAWAI_PHM_PROGRAM_SUPER_JET                ( 48)
#define KAWAI_PHM_PROGRAM_CANNON_AND_GUN           ( 49)
#define KAWAI_PHM_PROGRAM_RAIN                     ( 50)
#define KAWAI_PHM_PROGRAM_YES_NO                   ( 51)
#define KAWAI_PHM_PROGRAM_UMI_NEKO                 ( 52)
#define KAWAI_PHM_PROGRAM_TERMINATOR               ( 53)
#define KAWAI_PHM_PROGRAM_VISITORS                 ( 54)
#define KAWAI_PHM_PROGRAM_SCRATCH_1                ( 55)
#define KAWAI_PHM_PROGRAM_FAL_IN_ANGEL             ( 56)
#define KAWAI_PHM_PROGRAM_ARRANGEMENT              ( 57)
#define KAWAI_PHM_PROGRAM_SOLO_SAX                 ( 58)
#define KAWAI_PHM_PROGRAM_TRUMPET                  ( 59)
#define KAWAI_PHM_PROGRAM_INDIATOWN                ( 60)
#define KAWAI_PHM_PROGRAM_MOONRAKER                ( 61)
#define KAWAI_PHM_PROGRAM_AMAZING                  ( 62)
#define KAWAI_PHM_PROGRAM_SPACE_NINJA              ( 63)
#define KAWAI_PHM_PROGRAM_OKOTO                    ( 64)
#define KAWAI_PHM_PROGRAM_STRAVINSKY               ( 65)
#define KAWAI_PHM_PROGRAM_ORCHESTRA                ( 66)
#define KAWAI_PHM_PROGRAM_ACCORDION                ( 67)
#define KAWAI_PHM_PROGRAM_ORIENTBELL               ( 68)
#define KAWAI_PHM_PROGRAM_GLITTY_CLAV              ( 69)
#define KAWAI_PHM_PROGRAM_KILTBLOWER               ( 70)
#define KAWAI_PHM_PROGRAM_CELLOS                   ( 71)
#define KAWAI_PHM_PROGRAM_PAN_FLUTE                ( 72)
#define KAWAI_PHM_PROGRAM_GLASSY                   ( 73)
#define KAWAI_PHM_PROGRAM_SINGLE_HIT               ( 74)
#define KAWAI_PHM_PROGRAM_BLUE_MONICA              ( 75)
#define KAWAI_PHM_PROGRAM_ANALOG_HORN              ( 76)
#define KAWAI_PHM_PROGRAM_NATURE_HORN              ( 77)
#define KAWAI_PHM_PROGRAM_HARPSICHORD              ( 78)
#define KAWAI_PHM_PROGRAM_OBOE                     ( 79)
#define KAWAI_PHM_PROGRAM_ECHOPLEX                 ( 80)
#define KAWAI_PHM_PROGRAM_BRITE_VIBE               ( 81)
#define KAWAI_PHM_PROGRAM_WINE_GLASS               ( 82)
#define KAWAI_PHM_PROGRAM_SOLO_VIOLIN              ( 83)
#define KAWAI_PHM_PROGRAM_AHH                      ( 84)
#define KAWAI_PHM_PROGRAM_WHISTLE                  ( 85)
#define KAWAI_PHM_PROGRAM_SITAR                    ( 86)
#define KAWAI_PHM_PROGRAM_JANS_THEME               ( 87)
#define KAWAI_PHM_PROGRAM_CHRYSALIS                ( 88)
#define KAWAI_PHM_PROGRAM_FIDDLER                  ( 89)
#define KAWAI_PHM_PROGRAM_KICK_PLUS_SNARE_1        ( 90)
#define KAWAI_PHM_PROGRAM_CYMBALS                  ( 91)
#define KAWAI_PHM_PROGRAM_A_TOM_PLUS_HI_HAT        ( 92)
#define KAWAI_PHM_PROGRAM_BONGO_COWBOY             ( 93)
#define KAWAI_PHM_PROGRAM_STEEL_DRUM               ( 94)
#define KAWAI_PHM_PROGRAM_TIMPANI                  ( 95)
#define KAWAI_PHM_PROGRAM_MARIMBA                  ( 96)
#define KAWAI_PHM_PROGRAM_TAMBOURINE               ( 97)
#define KAWAI_PHM_PROGRAM_CASTANET                 ( 98)
#define KAWAI_PHM_PROGRAM_BOTTLE_BELL              ( 99)
#define KAWAI_PHM_PROGRAM_ALS_RODES                (100)
#define KAWAI_PHM_PROGRAM_EBONY_AND_IVORY          (101)
#define KAWAI_PHM_PROGRAM_FLANGE_GRAND             (102)
#define KAWAI_PHM_PROGRAM_FM_RODES                 (103)
#define KAWAI_PHM_PROGRAM_SMALL_GRAND              (104)
#define KAWAI_PHM_PROGRAM_ELECTRIC_GRAND_PIANO_2   (105)
#define KAWAI_PHM_PROGRAM_BLUE_NOTE                (106)
#define KAWAI_PHM_PROGRAM_BASS_GUITAR_2            (107)
#define KAWAI_PHM_PROGRAM_FRETLESS                 (108)
#define KAWAI_PHM_PROGRAM_ROUND_BASS               (109)
#define KAWAI_PHM_PROGRAM_KICK_BASS_2              (110)
#define KAWAI_PHM_PROGRAM_BOWED_STRINGS            (111)
#define KAWAI_PHM_PROGRAM_ANALOG_BRASS_2           (112)
#define KAWAI_PHM_PROGRAM_BRASS_ENSEMBLE_3         (113)
#define KAWAI_PHM_PROGRAM_BRASS_ENSEMBLE_4         (114)
#define KAWAI_PHM_PROGRAM_BRASSTRIX                (115)
#define KAWAI_PHM_PROGRAM_OB_BRASS                 (116)
#define KAWAI_PHM_PROGRAM_PROFET_PAD               (117)
#define KAWAI_PHM_PROGRAM_CLAV_GUITAR              (118)
#define KAWAI_PHM_PROGRAM_FUNK_GUITAR              (119)
#define KAWAI_PHM_PROGRAM_FEED_BACK                (120)
#define KAWAI_PHM_PROGRAM_MUTE_GUITAR              (121)
#define KAWAI_PHM_PROGRAM_STEEL_YARD               (122)
#define KAWAI_PHM_PROGRAM_12_STRING                (123)
#define KAWAI_PHM_PROGRAM_RED_ONIONS               (124)
#define KAWAI_PHM_PROGRAM_LES_LEE                  (125)
#define KAWAI_PHM_PROGRAM_X_FADE_ORGAN             (126)
#define KAWAI_PHM_PROGRAM_DRAWBER                  (127)
#define KAWAI_PHM_PROGRAM_NEAL_LARSEN              (128)
#define KAWAI_PHM_PROGRAM_STRING_WASH              (129)
#define KAWAI_PHM_PROGRAM_REVELATION               (130)
#define KAWAI_PHM_PROGRAM_DEEP_STRING              (131)
#define KAWAI_PHM_PROGRAM_ANALOG_STRING            (132)
#define KAWAI_PHM_PROGRAM_BOWED_STRING             (133)
#define KAWAI_PHM_PROGRAM_STRING_ENSEMBLE          (134)
#define KAWAI_PHM_PROGRAM_STRINGSTIC               (135)
#define KAWAI_PHM_PROGRAM_BACKIN_SY_2              (136)
#define KAWAI_PHM_PROGRAM_SYN_SOLO_2               (137)
#define KAWAI_PHM_PROGRAM_SQUEEZE_SQUARE           (138)
#define KAWAI_PHM_PROGRAM_ALLEZ_HOP                (139)
#define KAWAI_PHM_PROGRAM_SYNTH_STRINGS            (140)
#define KAWAI_PHM_PROGRAM_FLEX_SOLO                (141)
#define KAWAI_PHM_PROGRAM_SYNTH_ENSEMBLE           (142)
#define KAWAI_PHM_PROGRAM_SYNTH_PAD                (143)
#define KAWAI_PHM_PROGRAM_INSECT_FACE              (144)
#define KAWAI_PHM_PROGRAM_SLASHER                  (145)
#define KAWAI_PHM_PROGRAM_FEEL_BAD                 (146)
#define KAWAI_PHM_PROGRAM_HELICOPTER               (147)
#define KAWAI_PHM_PROGRAM_HOLD_A_KEY               (148)
#define KAWAI_PHM_PROGRAM_UAM_UAM_UAM_U            (149)
#define KAWAI_PHM_PROGRAM_BIRD_CALL                (150)
#define KAWAI_PHM_PROGRAM_KATANA                   (151)
#define KAWAI_PHM_PROGRAM_DOPPLER                  (152)
#define KAWAI_PHM_PROGRAM_NINJA                    (153)
#define KAWAI_PHM_PROGRAM_FLIMMER                  (154)
#define KAWAI_PHM_PROGRAM_SCRATCH_2                (155)
#define KAWAI_PHM_PROGRAM_ON_THE_EDGE              (156)
#define KAWAI_PHM_PROGRAM_PARADOX                  (157)
#define KAWAI_PHM_PROGRAM_TENOR_SAX                (158)
#define KAWAI_PHM_PROGRAM_SAFE_SAX                 (159)
#define KAWAI_PHM_PROGRAM_LOTSAHORNS               (160)
#define KAWAI_PHM_PROGRAM_AMAZON                   (161)
#define KAWAI_PHM_PROGRAM_ISLANDS                  (162)
#define KAWAI_PHM_PROGRAM_KIMONO                   (163)
#define KAWAI_PHM_PROGRAM_MUSIC_BOX                (164)
#define KAWAI_PHM_PROGRAM_VOICE_ORCH               (165)
#define KAWAI_PHM_PROGRAM_FAIR_MARKET              (166)
#define KAWAI_PHM_PROGRAM_LIL_ITALY                (167)
#define KAWAI_PHM_PROGRAM_BELLERY                  (168)
#define KAWAI_PHM_PROGRAM_FUZZ_CLAV                (169)
#define KAWAI_PHM_PROGRAM_CLARINET                 (170)
#define KAWAI_PHM_PROGRAM_JAZZ_HARP                (171)
#define KAWAI_PHM_PROGRAM_FLUTE                    (172)
#define KAWAI_PHM_PROGRAM_FINE_GLASS               (173)
#define KAWAI_PHM_PROGRAM_REVERSE_HIT              (174)
#define KAWAI_PHM_PROGRAM_MOWAAAA                  (175)
#define KAWAI_PHM_PROGRAM_DIGI_HORN                (176)
#define KAWAI_PHM_PROGRAM_FRENCH_HORN              (177)
#define KAWAI_PHM_PROGRAM_TUBULAR                  (178)
#define KAWAI_PHM_PROGRAM_SEQUENCE_IT              (179)
#define KAWAI_PHM_PROGRAM_AFTER_PRESS              (180)
#define KAWAI_PHM_PROGRAM_VIBE_CHORUS              (181)
#define KAWAI_PHM_PROGRAM_REAL_VIBE                (182)
#define KAWAI_PHM_PROGRAM_PIZZICATO                (183)
#define KAWAI_PHM_PROGRAM_VOICE                    (184)
#define KAWAI_PHM_PROGRAM_MINI_SINE                (185)
#define KAWAI_PHM_PROGRAM_BOTTLE_WIND              (186)
#define KAWAI_PHM_PROGRAM_BELICHOIR                (187)
#define KAWAI_PHM_PROGRAM_AIR_COMP                 (188)
#define KAWAI_PHM_PROGRAM_FLANG_CRASH              (189)
#define KAWAI_PHM_PROGRAM_KICK_PLUS_SNARE_2        (190)
#define KAWAI_PHM_PROGRAM_GATED_KICK_AND_SNARE     (191)
#define KAWAI_PHM_PROGRAM_TOM_SLAP                 (192)
#define KAWAI_PHM_PROGRAM_CONGA_ANGLE              (193)
#define KAWAI_PHM_PROGRAM_ETHNO_PERCUSSION         (194)
#define KAWAI_PHM_PROGRAM_BOTTLES                  (195)
#define KAWAI_PHM_PROGRAM_FINGER_SNAP              (196)
#define KAWAI_PHM_PROGRAM_WOODCUTTER               (197)
#define KAWAI_PHM_PROGRAM_XYLIMBA                  (198)
#define KAWAI_PHM_PROGRAM_GLASS_CUP                (199)

#define KAWAI_PHM_PERCUSSION_ACOUSTIC_BASS_DRUM    (36)
#define KAWAI_PHM_PERCUSSION_RIM_SHOT              (37)
#define KAWAI_PHM_PERCUSSION_ACOUSTIC_SNARE_DRUM   (38)
#define KAWAI_PHM_PERCUSSION_FINGER_SNAP           (39)
#define KAWAI_PHM_PERCUSSION_E_SNARE_DRUM          (40)
#define KAWAI_PHM_PERCUSSION_KICK_DRUM             (41)
#define KAWAI_PHM_PERCUSSION_CLOSED_HI_HAT         (42)
#define KAWAI_PHM_PERCUSSION_LOW_TOM               (43)
#define KAWAI_PHM_PERCUSSION_SCRATCH               (44)
#define KAWAI_PHM_PERCUSSION_HI_TOM                (45)
#define KAWAI_PHM_PERCUSSION_OPEN_HI_HAT           (46)
#define KAWAI_PHM_PERCUSSION_AGOGO                 (47)
#define KAWAI_PHM_PERCUSSION_COWBELL               (48)
#define KAWAI_PHM_PERCUSSION_CRASH_CYMBAL          (49)
#define KAWAI_PHM_PERCUSSION_SE_SNARE_DRUM         (50)
#define KAWAI_PHM_PERCUSSION_RIDE_CYMBAL           (51)

#define KAWAI_PHM_RANGE_INVALID                  (0x00)
#define KAWAI_PHM_RANGE_OCTAVE_HIGHER            (0x01)
#define KAWAI_PHM_RANGE_OCTAVE_LOWER             (0x02)
#define KAWAI_PHM_RANGE_LOWER_HALF               (0x03)
#define KAWAI_PHM_RANGE_DEFAULT                  (0x0F)

#endif
