#ifndef MIDIPLAN_DEVICES_YAMAHA_EMR1_H
#define MIDIPLAN_DEVICES_YAMAHA_EMR1_H

#include <midiplan/device.h>

extern const midiplan_device_t yamaha_emr1;

#define YAMAHA_EMR1_PERCUSSION_HI_HAT_CLOSED     (49)
#define YAMAHA_EMR1_PERCUSSION_HI_HAT_OPEN       (51)
#define YAMAHA_EMR1_PERCUSSION_CRASH_CYMBAL      (56)
#define YAMAHA_EMR1_PERCUSSION_SNARE_DRUM_HEAVY  (43)
#define YAMAHA_EMR1_PERCUSSION_BASS_DRUM         (41)
#define YAMAHA_EMR1_PERCUSSION_HI_HAT_PEDAL      (46)
#define YAMAHA_EMR1_PERCUSSION_RIDE_CYMBAL       (54)
#define YAMAHA_EMR1_PERCUSSION_SNARE_DRUM_LIGHT  (45)
#define YAMAHA_EMR1_PERCUSSION_SNARE_DRUM_ECHO   (47)
#define YAMAHA_EMR1_PERCUSSION_BRUSH             (44)
#define YAMAHA_EMR1_PERCUSSION_RIM               (42)
#define YAMAHA_EMR1_PERCUSSION_TOM_1             (53)
#define YAMAHA_EMR1_PERCUSSION_TOM_2             (52)
#define YAMAHA_EMR1_PERCUSSION_TOM_3             (50)
#define YAMAHA_EMR1_PERCUSSION_ELECTRONIC_TOM_1  (59)
#define YAMAHA_EMR1_PERCUSSION_ELECTRONIC_TOM_2  (57)
#define YAMAHA_EMR1_PERCUSSION_ELECTRONIC_TOM_3  (55)
#define YAMAHA_EMR1_PERCUSSION_CONGA_HIGH        (62)
#define YAMAHA_EMR1_PERCUSSION_CONGA_LOW         (60)
#define YAMAHA_EMR1_PERCUSSION_TIMBALE_HIGH      (67)
#define YAMAHA_EMR1_PERCUSSION_TIMBALE_LOW       (65)
#define YAMAHA_EMR1_PERCUSSION_CUICA_HIGH        (71)
#define YAMAHA_EMR1_PERCUSSION_CUICA_LOW         (69)
#define YAMAHA_EMR1_PERCUSSION_AGOGO_HIGH        (75)
#define YAMAHA_EMR1_PERCUSSION_AGOGO_LOW         (73)
#define YAMAHA_EMR1_PERCUSSION_COWBELL           (70)
#define YAMAHA_EMR1_PERCUSSION_BONGO             (64)
#define YAMAHA_EMR1_PERCUSSION_TAMBOURINE        (78)
#define YAMAHA_EMR1_PERCUSSION_TRIANGLE_CLOSED   (80)
#define YAMAHA_EMR1_PERCUSSION_TRIANGLE_OPEN     (82)
#define YAMAHA_EMR1_PERCUSSION_HAND_CLAPS        (72)
#define YAMAHA_EMR1_PERCUSSION_CASTANETS         (68)
#define YAMAHA_EMR1_PERCUSSION_WOODBLOCK_HIGH    (66)
#define YAMAHA_EMR1_PERCUSSION_WOODBLOCK_LOW     (63)
#define YAMAHA_EMR1_PERCUSSION_SHAKER            (61)
#define YAMAHA_EMR1_PERCUSSION_TOM_4             (48)
#define YAMAHA_EMR1_PERCUSSION_REVERSED_CYMBAL   (58)

#define YAMAHA_EMR1_RANGE_INVALID              (0x00)

#endif
