#ifndef MIDIPLAN_DEVICES_YAMAHA_RX21_H
#define MIDIPLAN_DEVICES_YAMAHA_RX21_H

#include <midiplan/device.h>

extern const midiplan_device_t yamaha_rx21;

#define YAMAHA_RX21_PERCUSSION_BASS_DRUM        (45)
#define YAMAHA_RX21_PERCUSSION_FLOOR_TOM_14     (48) 
#define YAMAHA_RX21_PERCUSSION_DEEP_BODY_TOM_12 (50) 
#define YAMAHA_RX21_PERCUSSION_SNARE_DRUM       (52)
#define YAMAHA_RX21_PERCUSSION_DEEP_BODY_TOM_10 (53) 
#define YAMAHA_RX21_PERCUSSION_HAND_CLAPS       (54)
#define YAMAHA_RX21_PERCUSSION_CLOSED_HI_HAT    (57) 
#define YAMAHA_RX21_PERCUSSION_OPEN_HI_HAT      (59) 
#define YAMAHA_RX21_PERCUSSION_CRASH_CYMBAL     (60)  

#define YAMAHA_RX21_RANGE_INVALID             (0x00)

#endif
