#ifndef MIDIPLAN_DEVICES_YAMAHA_DOM30_H
#define MIDIPLAN_DEVICES_YAMAHA_DOM30_H

#include <midiplan/device.h>

extern const midiplan_device_t yamaha_dom30;

#define YAMAHA_DOM30_LOWEST_NOTE   (21)
#define YAMAHA_DOM30_MIDDLE_C      (60)
#define YAMAHA_DOM30_HIGHEST_NOTE (108)

#define YAMAHA_DOM30_PROGRAM_PIANO_1                  ( 0)
#define YAMAHA_DOM30_PROGRAM_PIANO_2                  ( 1)
#define YAMAHA_DOM30_PROGRAM_HONKY_TONK_PIANO         ( 2)
#define YAMAHA_DOM30_PROGRAM_E_PIANO_1                ( 3)
#define YAMAHA_DOM30_PROGRAM_E_PIANO_2                ( 4)
#define YAMAHA_DOM30_PROGRAM_E_PIANO_3                ( 5)
#define YAMAHA_DOM30_PROGRAM_E_PIANO_4                ( 6)
#define YAMAHA_DOM30_PROGRAM_SYNTH_PIANO              ( 7)
#define YAMAHA_DOM30_PROGRAM_CELESTA                  ( 8)
#define YAMAHA_DOM30_PROGRAM_MARIMBA                  ( 9)
#define YAMAHA_DOM30_PROGRAM_BAMBOO_MARIMBA           (10)
#define YAMAHA_DOM30_PROGRAM_KALIMBA                  (11)
#define YAMAHA_DOM30_PROGRAM_VIBES                    (12)
#define YAMAHA_DOM30_PROGRAM_MUSIC_BOX                (13)
#define YAMAHA_DOM30_PROGRAM_SYNTH_CRYSTAL            (14)
#define YAMAHA_DOM30_PROGRAM_CLAVI                    (15)
#define YAMAHA_DOM30_PROGRAM_SYNTH_CLAVI              (16)
#define YAMAHA_DOM30_PROGRAM_JAZZ_ORGAN_1             (17)
#define YAMAHA_DOM30_PROGRAM_JAZZ_ORGAN_2             (18)
#define YAMAHA_DOM30_PROGRAM_ROCK_ORGAN               (19)
#define YAMAHA_DOM30_PROGRAM_PIPE_ORGAN               (20)
#define YAMAHA_DOM30_PROGRAM_FOLK_GUITAR              (21)
#define YAMAHA_DOM30_PROGRAM_12_STR_GUITAR            (22)
#define YAMAHA_DOM30_PROGRAM_ACOUSTIC_GUITAR          (23)
#define YAMAHA_DOM30_PROGRAM_JAZZ_GUITAR              (24)
#define YAMAHA_DOM30_PROGRAM_ROCK_GUITAR_1            (25)
#define YAMAHA_DOM30_PROGRAM_ROCK_GUITAR_2            (26)
#define YAMAHA_DOM30_PROGRAM_DISTORTION_GUITAR        (27)
#define YAMAHA_DOM30_PROGRAM_MUTE_GUITAR              (28)
#define YAMAHA_DOM30_PROGRAM_BANJO                    (29)
#define YAMAHA_DOM30_PROGRAM_SITAR                    (30)
#define YAMAHA_DOM30_PROGRAM_HARP                     (31)
#define YAMAHA_DOM30_PROGRAM_KOTO                     (32)
#define YAMAHA_DOM30_PROGRAM_HARPSICHORD_1            (33)
#define YAMAHA_DOM30_PROGRAM_HARPSICHORD_2            (34)
#define YAMAHA_DOM30_PROGRAM_HARPSICHORD_3            (35)
#define YAMAHA_DOM30_PROGRAM_E_BASS_1                 (36)
#define YAMAHA_DOM30_PROGRAM_E_BASS_2                 (37)
#define YAMAHA_DOM30_PROGRAM_E_BASS_3                 (38)
#define YAMAHA_DOM30_PROGRAM_SLAP_BASS                (39)
#define YAMAHA_DOM30_PROGRAM_SYNTH_BASS_1             (40)
#define YAMAHA_DOM30_PROGRAM_SYNTH_BASS_2             (41)
#define YAMAHA_DOM30_PROGRAM_SYNTH_BASS_3             (42)
#define YAMAHA_DOM30_PROGRAM_UPRIGHT_BASS_1           (43)
#define YAMAHA_DOM30_PROGRAM_UPRIGHT_BASS_2           (44)
#define YAMAHA_DOM30_PROGRAM_UPRIGHT_BASS_3           (45)
#define YAMAHA_DOM30_PROGRAM_VIOLIN_CELLO             (46)
#define YAMAHA_DOM30_PROGRAM_PIZZICATO                (47)
#define YAMAHA_DOM30_PROGRAM_STRINGS_1                (48)
#define YAMAHA_DOM30_PROGRAM_STRINGS_2                (49)
#define YAMAHA_DOM30_PROGRAM_SYNTH_STRINGS_1          (50)
#define YAMAHA_DOM30_PROGRAM_SYNTH_STRINGS_2          (51)
#define YAMAHA_DOM30_PROGRAM_ORCHESTRA_HIT            (52)
#define YAMAHA_DOM30_PROGRAM_TRUMPET_TROMBONE         (53)
#define YAMAHA_DOM30_PROGRAM_MUTE_TRUMPET             (54)
#define YAMAHA_DOM30_PROGRAM_HORN                     (55)
#define YAMAHA_DOM30_PROGRAM_BRASS_1                  (56)
#define YAMAHA_DOM30_PROGRAM_BRASS_2                  (57)
#define YAMAHA_DOM30_PROGRAM_SYNTH_BRASS_1            (58)
#define YAMAHA_DOM30_PROGRAM_SYNTH_BRASS_2            (59)
#define YAMAHA_DOM30_PROGRAM_SYNTH_BRASS_3            (60)
#define YAMAHA_DOM30_PROGRAM_SAX                      (61)
#define YAMAHA_DOM30_PROGRAM_CLARINET                 (62)
#define YAMAHA_DOM30_PROGRAM_RECORDER                 (63)
#define YAMAHA_DOM30_PROGRAM_FLUTE                    (64)
#define YAMAHA_DOM30_PROGRAM_PAN_FLUTE                (65)
#define YAMAHA_DOM30_PROGRAM_OBOE                     (66)
#define YAMAHA_DOM30_PROGRAM_BASSOON                  (67)
#define YAMAHA_DOM30_PROGRAM_BAGPIPE                  (68)
#define YAMAHA_DOM30_PROGRAM_HARMONICA                (69)
#define YAMAHA_DOM30_PROGRAM_ACCORDION                (70)
#define YAMAHA_DOM30_PROGRAM_SYNTH_1                  (71)
#define YAMAHA_DOM30_PROGRAM_SYNTH_2                  (72)
#define YAMAHA_DOM30_PROGRAM_SYNTH_3                  (73)
#define YAMAHA_DOM30_PROGRAM_SYNTH_4                  (74)
#define YAMAHA_DOM30_PROGRAM_SYNTH_5                  (75)
#define YAMAHA_DOM30_PROGRAM_DRUMS                    (76)
#define YAMAHA_DOM30_PROGRAM_TIMPANI_STEEL_DRUM       (77)
#define YAMAHA_DOM30_PROGRAM_AFRICAN_PERCUS           (78)
#define YAMAHA_DOM30_PROGRAM_GAMELAN                  (79)
#define YAMAHA_DOM30_PROGRAM_CHOIR                    (80)
#define YAMAHA_DOM30_PROGRAM_SYNTH_VOX_1              (81)
#define YAMAHA_DOM30_PROGRAM_SYNTH_VOX_2              (82)
#define YAMAHA_DOM30_PROGRAM_OW                       (83)
#define YAMAHA_DOM30_PROGRAM_AQUA                     (84)
#define YAMAHA_DOM30_PROGRAM_LANDSCAPE                (85)
#define YAMAHA_DOM30_PROGRAM_ICE_BLOCK                (86)
#define YAMAHA_DOM30_PROGRAM_CRYSTAL_BLOCK            (87)
#define YAMAHA_DOM30_PROGRAM_SAMBA_WHISTLE            (88)
#define YAMAHA_DOM30_PROGRAM_BIRDS                    (89)
#define YAMAHA_DOM30_PROGRAM_HAMMER_SHOT              (90)
#define YAMAHA_DOM30_PROGRAM_INVADER                  (91)
#define YAMAHA_DOM30_PROGRAM_SHOCK_ALARM              (92)
#define YAMAHA_DOM30_PROGRAM_WATER_DROP               (93)
#define YAMAHA_DOM30_PROGRAM_EMERGENCY                (94)
#define YAMAHA_DOM30_PROGRAM_ZING                     (95)
#define YAMAHA_DOM30_PROGRAM_RACING_CIRCUIT           (96)
#define YAMAHA_DOM30_PROGRAM_SCRAPE                   (97)
#define YAMAHA_DOM30_PROGRAM_CONSTRUCTION             (98)
#define YAMAHA_DOM30_PROGRAM_WAVE                     (99)

#define YAMAHA_DOM30_RANGE_INVALID                  (0x00)
#define YAMAHA_DOM30_RANGE_OCTAVE_HIGHER            (0x01)
#define YAMAHA_DOM30_RANGE_OCTAVE_LOWER             (0x02)
#define YAMAHA_DOM30_RANGE_DEFAULT                  (0x0F)

#define YAMAHA_DOM30_PERCUSSION_BRUSH_ROLL_1          (54)
#define YAMAHA_DOM30_PERCUSSION_HI_HAT_CLOSED_HEAVY   (56)
#define YAMAHA_DOM30_PERCUSSION_CRASH_CYMBAL_LIGHT    (58)
#define YAMAHA_DOM30_PERCUSSION_BASS_DRUM_LIGHT       (59)
#define YAMAHA_DOM30_PERCUSSION_SNARE_DRUM_RIM_HEAVY  (60)
#define YAMAHA_DOM30_PERCUSSION_RIDE_CYMBAL_CUP       (61)
#define YAMAHA_DOM30_PERCUSSION_SNARE_DRUM_RIM_LIGHT  (62)
#define YAMAHA_DOM30_PERCUSSION_BASS_DRUM             (65)
#define YAMAHA_DOM30_PERCUSSION_RIM_SHOT              (66)
#define YAMAHA_DOM30_PERCUSSION_SNARE_DRUM_HEAVY      (67)
#define YAMAHA_DOM30_PERCUSSION_BRUSH_SHOT            (68)
#define YAMAHA_DOM30_PERCUSSION_SNARE_DRUM_LIGHT      (69)
#define YAMAHA_DOM30_PERCUSSION_HI_HAT_PEDAL          (70)
#define YAMAHA_DOM30_PERCUSSION_SNARE_DRUM_ECHO       (71)
#define YAMAHA_DOM30_PERCUSSION_TOM_4                 (72)
#define YAMAHA_DOM30_PERCUSSION_HI_HAT_CLOSED         (73)
#define YAMAHA_DOM30_PERCUSSION_TOM_3                 (74)
#define YAMAHA_DOM30_PERCUSSION_HI_HAT_OPEN           (75)
#define YAMAHA_DOM30_PERCUSSION_TOM_2                 (76)
#define YAMAHA_DOM30_PERCUSSION_TOM_1                 (77)
#define YAMAHA_DOM30_PERCUSSION_RIDE_CYMBAL           (78)
#define YAMAHA_DOM30_PERCUSSION_ELECTRONIC_TOM_3      (79)
#define YAMAHA_DOM30_PERCUSSION_CRASH_CYMBAL_1        (80)
#define YAMAHA_DOM30_PERCUSSION_ELECTRONIC_TOM_2_1    (81)
#define YAMAHA_DOM30_PERCUSSION_CRASH_CYMBAL_2        (82)
#define YAMAHA_DOM30_PERCUSSION_ELECTRONIC_TOM_1      (83)
#define YAMAHA_DOM30_PERCUSSION_CONGA_LOW             (84)
#define YAMAHA_DOM30_PERCUSSION_CABASA                (85)
#define YAMAHA_DOM30_PERCUSSION_CONGA_HIGH            (86)
#define YAMAHA_DOM30_PERCUSSION_METRONOME             (87)
#define YAMAHA_DOM30_PERCUSSION_BONGO                 (88)
#define YAMAHA_DOM30_PERCUSSION_TIMBALE_LOW           (89)
#define YAMAHA_DOM30_PERCUSSION_CLAVES                (90)
#define YAMAHA_DOM30_PERCUSSION_TIMBALE_HIGH          (91)
#define YAMAHA_DOM30_PERCUSSION_CASTANETS             (92)
#define YAMAHA_DOM30_PERCUSSION_CUICA_LOW             (93)
#define YAMAHA_DOM30_PERCUSSION_COWBELL               (94)
#define YAMAHA_DOM30_PERCUSSION_CUICA_HIGH            (95)
#define YAMAHA_DOM30_PERCUSSION_HAND_CLAPS            (96)
#define YAMAHA_DOM30_PERCUSSION_AGOGO_LOW             (97)
#define YAMAHA_DOM30_PERCUSSION_AGOGO_HIGH            (99)
#define YAMAHA_DOM30_PERCUSSION_BONGO_LOW             (100)
#define YAMAHA_DOM30_PERCUSSION_ELECTRONIC_TOM_2_2    (101)
#define YAMAHA_DOM30_PERCUSSION_TAMBOURINE            (102)
#define YAMAHA_DOM30_PERCUSSION_CRASH_CYMBAL_3        (103)
#define YAMAHA_DOM30_PERCUSSION_TRIANGLE_CLOSED       (104)
#define YAMAHA_DOM30_PERCUSSION_BRUSH_ROLL_2          (105)
#define YAMAHA_DOM30_PERCUSSION_TRIANGLE_OPEN         (106)

#endif
