#!/usr/bin/python3

import re

GM_PROGRAM_ACOUSTIC_GRAND_PIANO     = 0x00
GM_PROGRAM_BRIGHT_ACOUSTIC_PIANO    = 0x01
GM_PROGRAM_ELECTRIC_GRAND_PIANO     = 0x02
GM_PROGRAM_HONKY_TONK_PIANO         = 0x03
GM_PROGRAM_ELECTRIC_PIANO_1         = 0x04
GM_PROGRAM_ELECTRIC_PIANO_2         = 0x05
GM_PROGRAM_HARPSICHORD              = 0x06
GM_PROGRAM_CLAVI                    = 0x07
GM_PROGRAM_CELESTA                  = 0x08
GM_PROGRAM_GLOCKENSPIEL             = 0x09
GM_PROGRAM_MUSIC_BOX                = 0x0A
GM_PROGRAM_VIBRAPHONE               = 0x0B
GM_PROGRAM_MARIMBA                  = 0x0C
GM_PROGRAM_XYLOPHONE                = 0x0D
GM_PROGRAM_TUBULAR_BELLS            = 0x0E
GM_PROGRAM_DULCIMER                 = 0x0F
GM_PROGRAM_DRAWBAR_ORGAN            = 0x10
GM_PROGRAM_PERCUSSIVE_ORGAN         = 0x11
GM_PROGRAM_ROCK_ORGAN               = 0x12
GM_PROGRAM_CHURCH_ORGAN             = 0x13
GM_PROGRAM_REED_ORGAN               = 0x14
GM_PROGRAM_ACCORDION                = 0x15
GM_PROGRAM_HARMONICA                = 0x16
GM_PROGRAM_TANGO_ACCORDION          = 0x17
GM_PROGRAM_ACOUSTIC_GUITAR_NYLON    = 0x18
GM_PROGRAM_ACOUSTIC_GUITAR_STEEL    = 0x19
GM_PROGRAM_ELECTRIC_GUITAR_JAZZ     = 0x1A
GM_PROGRAM_ELECTRIC_GUITAR_CLEAN    = 0x1B
GM_PROGRAM_ELECTRIC_GUITAR_MUTED    = 0x1C
GM_PROGRAM_OVERDRIVEN_GUITAR        = 0x1D
GM_PROGRAM_DISTORTION_GUITAR        = 0x1E
GM_PROGRAM_GUITAR_HARMONICS         = 0x1F
GM_PROGRAM_ACOUSTIC_BASS            = 0x20
GM_PROGRAM_ELECTRIC_BASS_FINGER     = 0x21
GM_PROGRAM_ELECTRIC_BASS_PICK       = 0x22
GM_PROGRAM_FRETLESS_BASS            = 0x23
GM_PROGRAM_SLAP_BASS_1              = 0x24
GM_PROGRAM_SLAP_BASS_2              = 0x25
GM_PROGRAM_SYNTH_BASS_1             = 0x26
GM_PROGRAM_SYNTH_BASS_2             = 0x27
GM_PROGRAM_VIOLIN                   = 0x28
GM_PROGRAM_VIOLA                    = 0x29
GM_PROGRAM_CELLO                    = 0x2A
GM_PROGRAM_CONTRABASS               = 0x2B
GM_PROGRAM_TREMOLO_STRINGS          = 0x2C
GM_PROGRAM_PIZZICATO_STRINGS        = 0x2D
GM_PROGRAM_ORCHESTRAL_HARP          = 0x2E
GM_PROGRAM_TIMPANI                  = 0x2F
GM_PROGRAM_STRING_ENSEMBLE_1        = 0x30
GM_PROGRAM_STRING_ENSEMBLE_2        = 0x31
GM_PROGRAM_SYNTHSTRINGS_1           = 0x32
GM_PROGRAM_SYNTHSTRINGS_2           = 0x33
GM_PROGRAM_CHOIR_AAHS               = 0x34
GM_PROGRAM_VOICE_OOHS               = 0x35
GM_PROGRAM_SYNTH_VOICE              = 0x36
GM_PROGRAM_ORCHESTRA_HIT            = 0x37
GM_PROGRAM_TRUMPET                  = 0x38
GM_PROGRAM_TROMBONE                 = 0x39
GM_PROGRAM_TUBA                     = 0x3A
GM_PROGRAM_MUTED_TRUMPET            = 0x3B
GM_PROGRAM_FRENCH_HORN              = 0x3C
GM_PROGRAM_BRASS_SECTION            = 0x3D
GM_PROGRAM_SYNTHBRASS_1             = 0x3E
GM_PROGRAM_SYNTHBRASS_2             = 0x3F
GM_PROGRAM_SOPRANO_SAX              = 0x40
GM_PROGRAM_ALTO_SAX                 = 0x41
GM_PROGRAM_TENOR_SAX                = 0x42
GM_PROGRAM_BARITONE_SAX             = 0x43
GM_PROGRAM_OBOE                     = 0x44
GM_PROGRAM_ENGLISH_HORN             = 0x45
GM_PROGRAM_BASSOON                  = 0x46
GM_PROGRAM_CLARINET                 = 0x47
GM_PROGRAM_PICCOLO                  = 0x48
GM_PROGRAM_FLUTE                    = 0x49
GM_PROGRAM_RECORDER                 = 0x4A
GM_PROGRAM_PAN_FLUTE                = 0x4B
GM_PROGRAM_BLOWN_BOTTLE             = 0x4C
GM_PROGRAM_SHAKUHACHI               = 0x4D
GM_PROGRAM_WHISTLE                  = 0x4E
GM_PROGRAM_OCARINA                  = 0x4F
GM_PROGRAM_LEAD_1_SQUARE            = 0x50
GM_PROGRAM_LEAD_2_SAWTOOTH          = 0x51
GM_PROGRAM_LEAD_3_CALLIOPE          = 0x52
GM_PROGRAM_LEAD_4_CHIFF             = 0x53
GM_PROGRAM_LEAD_5_CHARANG           = 0x54
GM_PROGRAM_LEAD_6_VOICE             = 0x55
GM_PROGRAM_LEAD_7_FIFTHS            = 0x56
GM_PROGRAM_LEAD_8_BASS_LEAD         = 0x57
GM_PROGRAM_PAD_1_NEW_AGE            = 0x58
GM_PROGRAM_PAD_2_WARM               = 0x59
GM_PROGRAM_PAD_3_POLYSYNTH          = 0x5A
GM_PROGRAM_PAD_4_CHOIR              = 0x5B
GM_PROGRAM_PAD_5_BOWED              = 0x5C
GM_PROGRAM_PAD_6_METALLIC           = 0x5D
GM_PROGRAM_PAD_7_HALO               = 0x5E
GM_PROGRAM_PAD_8_SWEEP              = 0x5F
GM_PROGRAM_FX_1_RAIN                = 0x60
GM_PROGRAM_FX_2_SOUNDTRACK          = 0x61
GM_PROGRAM_FX_3_CRYSTAL             = 0x62
GM_PROGRAM_FX_4_ATMOSPHERE          = 0x63
GM_PROGRAM_FX_5_BRIGHTNESS          = 0x64
GM_PROGRAM_FX_6_GOBLINS             = 0x65
GM_PROGRAM_FX_7_ECHOES              = 0x66
GM_PROGRAM_FX_8_SCI_FI              = 0x67
GM_PROGRAM_SITAR                    = 0x68
GM_PROGRAM_BANJO                    = 0x69
GM_PROGRAM_SHAMISEN                 = 0x6A
GM_PROGRAM_KOTO                     = 0x6B
GM_PROGRAM_KALIMBA                  = 0x6C
GM_PROGRAM_BAG_PIPE                 = 0x6D
GM_PROGRAM_FIDDLE                   = 0x6E
GM_PROGRAM_SHANAI                   = 0x6F
GM_PROGRAM_TINKLE_BELL              = 0x70
GM_PROGRAM_AGOGO                    = 0x71
GM_PROGRAM_STEEL_DRUMS              = 0x72
GM_PROGRAM_WOODBLOCK                = 0x73
GM_PROGRAM_TAIKO_DRUM               = 0x74
GM_PROGRAM_MELODIC_TOM              = 0x75
GM_PROGRAM_SYNTH_DRUM               = 0x76
GM_PROGRAM_REVERSE_CYMBAL           = 0x77
GM_PROGRAM_GUITAR_FRET_NOISE        = 0x78
GM_PROGRAM_BREATH_NOISE             = 0x79
GM_PROGRAM_SEASHORE                 = 0x7A
GM_PROGRAM_BIRD_TWEET               = 0x7B
GM_PROGRAM_TELEPHONE_RING           = 0x7C
GM_PROGRAM_HELICOPTER               = 0x7D
GM_PROGRAM_APPLAUSE                 = 0x7E
GM_PROGRAM_GUNSHOT                  = 0x7F

ROLAND_CM32P_A_PIANO_1              = 0x00
ROLAND_CM32P_A_PIANO_2              = 0x01
ROLAND_CM32P_A_PIANO_3              = 0x02
ROLAND_CM32P_A_PIANO_4              = 0x03
ROLAND_CM32P_A_PIANO_5              = 0x04
ROLAND_CM32P_A_PIANO_7              = 0x05
ROLAND_CM32P_A_PIANO_9              = 0x06
ROLAND_CM32P_E_PIANO_1              = 0x07
ROLAND_CM32P_E_PIANO_3              = 0x08
ROLAND_CM32P_E_PIANO_5              = 0x09
ROLAND_CM32P_A_GUITAR_1             = 0x0A
ROLAND_CM32P_A_GUITAR_3             = 0x0B
ROLAND_CM32P_A_GUITAR_4             = 0x0C
ROLAND_CM32P_E_GUITAR_1             = 0x0D
ROLAND_CM32P_E_GUITAR_2             = 0x0E
ROLAND_CM32P_SLAP_3                 = 0x0F
ROLAND_CM32P_SLAP_4                 = 0x10
ROLAND_CM32P_SLAP_5                 = 0x11
ROLAND_CM32P_SLAP_6                 = 0x12
ROLAND_CM32P_SLAP_9                 = 0x13
ROLAND_CM32P_SLAP_10                = 0x14
ROLAND_CM32P_SLAP_11                = 0x15
ROLAND_CM32P_SLAP_12                = 0x16
ROLAND_CM32P_FINGERED_1             = 0x17
ROLAND_CM32P_FINGERED_2             = 0x18
ROLAND_CM32P_PICKED_1               = 0x19
ROLAND_CM32P_PICKED_2               = 0x1A
ROLAND_CM32P_FRETLESS_1             = 0x1B
ROLAND_CM32P_AC_BASS                = 0x1C
ROLAND_CM32P_CHOIR_1                = 0x1D
ROLAND_CM32P_CHOIR_2                = 0x1E
ROLAND_CM32P_CHOIR_3                = 0x1F
ROLAND_CM32P_CHOIR_4                = 0x20
ROLAND_CM32P_STRINGS_1              = 0x21
ROLAND_CM32P_STRINGS_2              = 0x22
ROLAND_CM32P_STRINGS_3              = 0x23
ROLAND_CM32P_STRINGS_4              = 0x24
ROLAND_CM32P_E_ORGAN_2              = 0x25
ROLAND_CM32P_E_ORGAN_4              = 0x26
ROLAND_CM32P_E_ORGAN_6              = 0x27
ROLAND_CM32P_E_ORGAN_8              = 0x28
ROLAND_CM32P_E_ORGAN_9              = 0x29
ROLAND_CM32P_E_ORGAN_10             = 0x2A
ROLAND_CM32P_E_ORGAN_11             = 0x2B
ROLAND_CM32P_E_ORGAN_12             = 0x2C
ROLAND_CM32P_E_ORGAN_13             = 0x2D
ROLAND_CM32P_SOFT_TP_1              = 0x2E
ROLAND_CM32P_SOFT_TP_3              = 0x2F
ROLAND_CM32P_TP_TRB_1               = 0x30
ROLAND_CM32P_TP_TRB_2               = 0x31
ROLAND_CM32P_TP_TRB_3               = 0x32
ROLAND_CM32P_TP_TRB_4               = 0x33
ROLAND_CM32P_TP_TRB_5               = 0x34
ROLAND_CM32P_TP_TRB_6               = 0x35
ROLAND_CM32P_SAX_1                  = 0x36
ROLAND_CM32P_SAX_2                  = 0x37
ROLAND_CM32P_SAX_3                  = 0x38
ROLAND_CM32P_SAX_5                  = 0x39
ROLAND_CM32P_BRASS_1                = 0x3A
ROLAND_CM32P_BRASS_2                = 0x3B
ROLAND_CM32P_BRASS_3                = 0x3C
ROLAND_CM32P_BRASS_4                = 0x3D
ROLAND_CM32P_BRASS_5                = 0x3E
ROLAND_CM32P_ORCHE_HIT              = 0x3F

hi = [
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x02, 0x02,
    0x02, 0x02, 0x02, 0x02, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x04, 0x04, 0x04, 0x04, 0x04,
    0x04, 0x04, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x09, 0x09, 0x09,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
]

lo = [
    0x08, 0x1B, 0x2E, 0x41, 0x54, 0x67, 0x7A, 0x0D, 0x20, 0x33, 0x46, 0x59, 0x6C, 0x7F, 0x12, 0x25,
    0x38, 0x4B, 0x5E, 0x71, 0x04, 0x17, 0x2A, 0x3D, 0x50, 0x63, 0x76, 0x09, 0x1C, 0x2F, 0x42, 0x55,
    0x68, 0x7B, 0x0E, 0x21, 0x34, 0x47, 0x5A, 0x6D, 0x00, 0x13, 0x26, 0x39, 0x4C, 0x5F, 0x72, 0x05,
    0x18, 0x2B, 0x3E, 0x51, 0x64, 0x77, 0x0A, 0x1D, 0x30, 0x43, 0x56, 0x69, 0x7C, 0x0F, 0x22, 0x35,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
]

mapping = """
GM_PROGRAM_ACOUSTIC_GRAND_PIANO  CM GM_PROGRAM_ACOUSTIC_GRAND_PIANO  ROLAND_CM32P_A_PIANO_1   
GM_PROGRAM_BRIGHT_ACOUSTIC_PIANO CM GM_PROGRAM_BRIGHT_ACOUSTIC_PIANO ROLAND_CM32P_A_PIANO_3   
GM_PROGRAM_ELECTRIC_GRAND_PIANO  CM GM_PROGRAM_ELECTRIC_GRAND_PIANO  ROLAND_CM32P_A_PIANO_7   
GM_PROGRAM_HONKY_TONK_PIANO      CM GM_PROGRAM_HONKY_TONK_PIANO      ROLAND_CM32P_A_PIANO_4   
GM_PROGRAM_ELECTRIC_PIANO_1      CM GM_PROGRAM_ELECTRIC_PIANO_1      ROLAND_CM32P_E_PIANO_3   
GM_PROGRAM_ELECTRIC_PIANO_2      CM GM_PROGRAM_ELECTRIC_PIANO_2      ROLAND_CM32P_E_PIANO_1   
GM_PROGRAM_HARPSICHORD              GM_PROGRAM_HARPSICHORD           ROLAND_CM32P_A_GUITAR_1  
GM_PROGRAM_CLAVI                    GM_PROGRAM_CLAVI                 ROLAND_CM32P_E_PIANO_5   
GM_PROGRAM_CELESTA                  GM_PROGRAM_CELESTA               ROLAND_CM32P_E_PIANO_3   
GM_PROGRAM_GLOCKENSPIEL             GM_PROGRAM_GLOCKENSPIEL          ROLAND_CM32P_E_PIANO_3   
GM_PROGRAM_MUSIC_BOX                GM_PROGRAM_MUSIC_BOX             ROLAND_CM32P_E_PIANO_5   
GM_PROGRAM_VIBRAPHONE               GM_PROGRAM_VIBRAPHONE            ROLAND_CM32P_E_PIANO_1   
GM_PROGRAM_MARIMBA                  GM_PROGRAM_MARIMBA               ROLAND_CM32P_E_PIANO_3   
GM_PROGRAM_XYLOPHONE                GM_PROGRAM_XYLOPHONE             ROLAND_CM32P_E_PIANO_3   
GM_PROGRAM_TUBULAR_BELLS            GM_PROGRAM_TUBULAR_BELLS         ROLAND_CM32P_E_PIANO_1   
GM_PROGRAM_DULCIMER              CM GM_PROGRAM_DULCIMER              ROLAND_CM32P_A_PIANO_7   
GM_PROGRAM_DRAWBAR_ORGAN         CM GM_PROGRAM_DRAWBAR_ORGAN         ROLAND_CM32P_E_ORGAN_2   
GM_PROGRAM_PERCUSSIVE_ORGAN      CM GM_PROGRAM_PERCUSSIVE_ORGAN      ROLAND_CM32P_E_ORGAN_8   
GM_PROGRAM_ROCK_ORGAN               GM_PROGRAM_ROCK_ORGAN            ROLAND_CM32P_E_ORGAN_8   
GM_PROGRAM_CHURCH_ORGAN             GM_PROGRAM_CHURCH_ORGAN          ROLAND_CM32P_E_ORGAN_10  
GM_PROGRAM_REED_ORGAN            CM GM_PROGRAM_REED_ORGAN            ROLAND_CM32P_SAX_2       
GM_PROGRAM_ACCORDION                GM_PROGRAM_ACCORDION             ROLAND_CM32P_TP_TRB_2    
GM_PROGRAM_HARMONICA                GM_PROGRAM_HARMONICA             ROLAND_CM32P_TP_TRB_2    
GM_PROGRAM_TANGO_ACCORDION          GM_PROGRAM_TANGO_ACCORDION       ROLAND_CM32P_TP_TRB_2    
GM_PROGRAM_ACOUSTIC_GUITAR_NYLON CM GM_PROGRAM_ACOUSTIC_GUITAR_NYLON ROLAND_CM32P_A_GUITAR_3  
GM_PROGRAM_ACOUSTIC_GUITAR_STEEL CM GM_PROGRAM_ACOUSTIC_GUITAR_STEEL ROLAND_CM32P_A_GUITAR_1  
GM_PROGRAM_ELECTRIC_GUITAR_JAZZ     GM_PROGRAM_ELECTRIC_GUITAR_JAZZ  ROLAND_CM32P_A_GUITAR_3  
GM_PROGRAM_ELECTRIC_GUITAR_CLEAN CM GM_PROGRAM_ELECTRIC_GUITAR_CLEAN ROLAND_CM32P_E_GUITAR_2  
GM_PROGRAM_ELECTRIC_GUITAR_MUTED CM GM_PROGRAM_ELECTRIC_GUITAR_MUTED ROLAND_CM32P_E_GUITAR_2  
GM_PROGRAM_OVERDRIVEN_GUITAR        GM_PROGRAM_OVERDRIVEN_GUITAR     ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_DISTORTION_GUITAR        GM_PROGRAM_DISTORTION_GUITAR     ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_GUITAR_HARMONICS         GM_PROGRAM_GUITAR_HARMONICS      ROLAND_CM32P_FINGERED_1  
GM_PROGRAM_ACOUSTIC_BASS         CM GM_PROGRAM_ACOUSTIC_BASS         ROLAND_CM32P_AC_BASS     
GM_PROGRAM_ELECTRIC_BASS_FINGER  CM GM_PROGRAM_ELECTRIC_BASS_FINGER  ROLAND_CM32P_FINGERED_1  
GM_PROGRAM_ELECTRIC_BASS_PICK    CM GM_PROGRAM_ELECTRIC_BASS_PICK    ROLAND_CM32P_PICKED_2    
GM_PROGRAM_FRETLESS_BASS         CM GM_PROGRAM_FRETLESS_BASS         ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_SLAP_BASS_1           CM GM_PROGRAM_SLAP_BASS_1           ROLAND_CM32P_SLAP_4      
GM_PROGRAM_SLAP_BASS_2           CM GM_PROGRAM_SLAP_BASS_2           ROLAND_CM32P_SLAP_3      
GM_PROGRAM_SYNTH_BASS_1          CM GM_PROGRAM_SYNTH_BASS_1          ROLAND_CM32P_FINGERED_2  
GM_PROGRAM_SYNTH_BASS_2             GM_PROGRAM_SYNTH_BASS_2          ROLAND_CM32P_FINGERED_2  
GM_PROGRAM_VIOLIN                   GM_PROGRAM_VIOLIN                ROLAND_CM32P_STRINGS_2   
GM_PROGRAM_VIOLA                    GM_PROGRAM_VIOLA                 ROLAND_CM32P_STRINGS_2   
GM_PROGRAM_CELLO                    GM_PROGRAM_CELLO                 ROLAND_CM32P_STRINGS_2   
GM_PROGRAM_CONTRABASS               GM_PROGRAM_CONTRABASS            ROLAND_CM32P_STRINGS_1   
GM_PROGRAM_TREMOLO_STRINGS       CM GM_PROGRAM_TREMOLO_STRINGS       ROLAND_CM32P_STRINGS_2   
GM_PROGRAM_PIZZICATO_STRINGS        GM_PROGRAM_PIZZICATO_STRINGS     ROLAND_CM32P_E_GUITAR_2  
GM_PROGRAM_ORCHESTRAL_HARP          GM_PROGRAM_ORCHESTRAL_HARP       ROLAND_CM32P_FINGERED_2  
GM_PROGRAM_TIMPANI                  GM_PROGRAM_TIMPANI               ROLAND_CM32P_E_PIANO_5   
GM_PROGRAM_STRING_ENSEMBLE_1     CM GM_PROGRAM_STRING_ENSEMBLE_1     ROLAND_CM32P_STRINGS_2   
GM_PROGRAM_STRING_ENSEMBLE_2     CM GM_PROGRAM_STRING_ENSEMBLE_2     ROLAND_CM32P_STRINGS_1   
GM_PROGRAM_SYNTHSTRINGS_1           GM_PROGRAM_SYNTHSTRINGS_1        ROLAND_CM32P_STRINGS_3   
GM_PROGRAM_SYNTHSTRINGS_2           GM_PROGRAM_SYNTHSTRINGS_2        ROLAND_CM32P_STRINGS_4   
GM_PROGRAM_CHOIR_AAHS            CM GM_PROGRAM_CHOIR_AAHS            ROLAND_CM32P_CHOIR_2     
GM_PROGRAM_VOICE_OOHS            CM GM_PROGRAM_VOICE_OOHS            ROLAND_CM32P_CHOIR_1     
GM_PROGRAM_SYNTH_VOICE              GM_PROGRAM_SYNTH_VOICE           ROLAND_CM32P_CHOIR_3     
GM_PROGRAM_ORCHESTRA_HIT         CM GM_PROGRAM_ORCHESTRA_HIT         ROLAND_CM32P_ORCHE_HIT   
GM_PROGRAM_TRUMPET               CM GM_PROGRAM_TRUMPET               ROLAND_CM32P_SOFT_TP_1   
GM_PROGRAM_TROMBONE              CM GM_PROGRAM_TROMBONE              ROLAND_CM32P_TP_TRB_2    
GM_PROGRAM_TUBA                  CM GM_PROGRAM_TUBA                  ROLAND_CM32P_SOFT_TP_1   
GM_PROGRAM_MUTED_TRUMPET         CM GM_PROGRAM_MUTED_TRUMPET         ROLAND_CM32P_TP_TRB_1    
GM_PROGRAM_FRENCH_HORN              GM_PROGRAM_FRENCH_HORN           ROLAND_CM32P_SAX_2       
GM_PROGRAM_BRASS_SECTION         CM GM_PROGRAM_BRASS_SECTION         ROLAND_CM32P_BRASS_4     
GM_PROGRAM_SYNTHBRASS_1             GM_PROGRAM_SYNTHBRASS_1          ROLAND_CM32P_BRASS_3     
GM_PROGRAM_SYNTHBRASS_2             GM_PROGRAM_SYNTHBRASS_2          ROLAND_CM32P_TP_TRB_5    
GM_PROGRAM_SOPRANO_SAX           CM GM_PROGRAM_SOPRANO_SAX           ROLAND_CM32P_SAX_2       
GM_PROGRAM_ALTO_SAX              CM GM_PROGRAM_ALTO_SAX              ROLAND_CM32P_SAX_1       
GM_PROGRAM_TENOR_SAX             CM GM_PROGRAM_TENOR_SAX             ROLAND_CM32P_SAX_3       
GM_PROGRAM_BARITONE_SAX          CM GM_PROGRAM_BARITONE_SAX          ROLAND_CM32P_SAX_5       
GM_PROGRAM_OBOE                  CM GM_PROGRAM_OBOE                  ROLAND_CM32P_SAX_2       
GM_PROGRAM_ENGLISH_HORN             GM_PROGRAM_ENGLISH_HORN          ROLAND_CM32P_SAX_2       
GM_PROGRAM_BASSOON                  GM_PROGRAM_BASSOON               ROLAND_CM32P_BRASS_1     
GM_PROGRAM_CLARINET                 GM_PROGRAM_CLARINET              ROLAND_CM32P_SAX_2       
GM_PROGRAM_PICCOLO                  GM_PROGRAM_PICCOLO               ROLAND_CM32P_BRASS_5     
GM_PROGRAM_FLUTE                    GM_PROGRAM_FLUTE                 ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_RECORDER                 GM_PROGRAM_RECORDER              ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_PAN_FLUTE                GM_PROGRAM_PAN_FLUTE             ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_BLOWN_BOTTLE             GM_PROGRAM_BLOWN_BOTTLE          ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_SHAKUHACHI               GM_PROGRAM_SHAKUHACHI            ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_WHISTLE                  GM_PROGRAM_WHISTLE               ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_OCARINA                  GM_PROGRAM_OCARINA               ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_LEAD_1_SQUARE            GM_PROGRAM_LEAD_1_SQUARE         ROLAND_CM32P_TP_TRB_2    
GM_PROGRAM_LEAD_2_SAWTOOTH          GM_PROGRAM_LEAD_2_SAWTOOTH       ROLAND_CM32P_BRASS_4     
GM_PROGRAM_LEAD_3_CALLIOPE          GM_PROGRAM_LEAD_3_CALLIOPE       ROLAND_CM32P_STRINGS_2   
GM_PROGRAM_LEAD_4_CHIFF             GM_PROGRAM_LEAD_4_CHIFF          ROLAND_CM32P_E_PIANO_5   
GM_PROGRAM_LEAD_5_CHARANG           GM_PROGRAM_LEAD_5_CHARANG        ROLAND_CM32P_TP_TRB_5    
GM_PROGRAM_LEAD_6_VOICE             GM_PROGRAM_LEAD_6_VOICE          ROLAND_CM32P_CHOIR_4     
GM_PROGRAM_LEAD_7_FIFTHS            GM_PROGRAM_LEAD_7_FIFTHS         ROLAND_CM32P_STRINGS_2   
GM_PROGRAM_LEAD_8_BASS_LEAD         GM_PROGRAM_LEAD_8_BASS_LEAD      ROLAND_CM32P_PICKED_2    
GM_PROGRAM_PAD_1_NEW_AGE            GM_PROGRAM_PAD_1_NEW_AGE         ROLAND_CM32P_E_PIANO_3   
GM_PROGRAM_PAD_2_WARM               GM_PROGRAM_PAD_2_WARM            ROLAND_CM32P_BRASS_5     
GM_PROGRAM_PAD_3_POLYSYNTH          GM_PROGRAM_PAD_3_POLYSYNTH       ROLAND_CM32P_STRINGS_1   
GM_PROGRAM_PAD_4_CHOIR           CM GM_PROGRAM_PAD_4_CHOIR           ROLAND_CM32P_CHOIR_3     
GM_PROGRAM_PAD_5_BOWED              GM_PROGRAM_PAD_5_BOWED           ROLAND_CM32P_E_PIANO_3   
GM_PROGRAM_PAD_6_METALLIC        CM GM_PROGRAM_PAD_6_METALLIC        ROLAND_CM32P_SLAP_6      
GM_PROGRAM_PAD_7_HALO               GM_PROGRAM_PAD_7_HALO            ROLAND_CM32P_E_PIANO_5   
GM_PROGRAM_PAD_8_SWEEP              GM_PROGRAM_PAD_8_SWEEP           ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_FX_1_RAIN             CM GM_PROGRAM_FX_1_RAIN             ROLAND_CM32P_FRETLESS_1  
GM_PROGRAM_FX_2_SOUNDTRACK          GM_PROGRAM_FX_2_SOUNDTRACK       ROLAND_CM32P_BRASS_1     
GM_PROGRAM_FX_3_CRYSTAL             GM_PROGRAM_FX_3_CRYSTAL          ROLAND_CM32P_E_PIANO_3   
GM_PROGRAM_FX_4_ATMOSPHERE          GM_PROGRAM_FX_4_ATMOSPHERE       ROLAND_CM32P_FINGERED_2  
GM_PROGRAM_FX_5_BRIGHTNESS          GM_PROGRAM_FX_5_BRIGHTNESS       ROLAND_CM32P_CHOIR_1     
GM_PROGRAM_FX_6_GOBLINS             GM_PROGRAM_FX_6_GOBLINS          ROLAND_CM32P_SLAP_5      
GM_PROGRAM_FX_7_ECHOES              GM_PROGRAM_FX_7_ECHOES           ROLAND_CM32P_PICKED_2    
GM_PROGRAM_FX_8_SCI_FI              GM_PROGRAM_FX_8_SCI_FI           ROLAND_CM32P_PICKED_2    
GM_PROGRAM_SITAR                    GM_PROGRAM_SITAR                 ROLAND_CM32P_SLAP_10     
GM_PROGRAM_BANJO                    GM_PROGRAM_BANJO                 ROLAND_CM32P_SLAP_4      
GM_PROGRAM_SHAMISEN                 GM_PROGRAM_SHAMISEN              ROLAND_CM32P_SLAP_10     
GM_PROGRAM_KOTO                     GM_PROGRAM_KOTO                  ROLAND_CM32P_SLAP_10     
GM_PROGRAM_KALIMBA                  GM_PROGRAM_KALIMBA               ROLAND_CM32P_SLAP_5      
GM_PROGRAM_BAG_PIPE                 GM_PROGRAM_BAG_PIPE              ROLAND_CM32P_TP_TRB_3    
GM_PROGRAM_FIDDLE                   GM_PROGRAM_FIDDLE                ROLAND_CM32P_STRINGS_2   
GM_PROGRAM_SHANAI                   GM_PROGRAM_SHANAI                ROLAND_CM32P_TP_TRB_5    
GM_PROGRAM_TINKLE_BELL              GM_PROGRAM_TINKLE_BELL           ROLAND_CM32P_E_PIANO_5   
GM_PROGRAM_AGOGO                    GM_PROGRAM_AGOGO                 ROLAND_CM32P_E_GUITAR_2  
GM_PROGRAM_STEEL_DRUMS              GM_PROGRAM_STEEL_DRUMS           ROLAND_CM32P_E_ORGAN_6   
GM_PROGRAM_WOODBLOCK                GM_PROGRAM_WOODBLOCK             ROLAND_CM32P_E_ORGAN_6   
GM_PROGRAM_TAIKO_DRUM               GM_PROGRAM_TAIKO_DRUM            ROLAND_CM32P_E_ORGAN_6   
GM_PROGRAM_MELODIC_TOM              GM_PROGRAM_MELODIC_TOM           ROLAND_CM32P_E_ORGAN_6   
GM_PROGRAM_SYNTH_DRUM               GM_PROGRAM_SYNTH_DRUM            ROLAND_CM32P_E_ORGAN_6   
GM_PROGRAM_REVERSE_CYMBAL           GM_PROGRAM_REVERSE_CYMBAL        ROLAND_CM32P_TP_TRB_3    
GM_PROGRAM_GUITAR_FRET_NOISE        GM_PROGRAM_GUITAR_FRET_NOISE     ROLAND_CM32P_SLAP_3      
GM_PROGRAM_BREATH_NOISE             GM_PROGRAM_BREATH_NOISE          ROLAND_CM32P_SOFT_TP_3   
GM_PROGRAM_SEASHORE                 GM_PROGRAM_SEASHORE              ROLAND_CM32P_TP_TRB_5    
GM_PROGRAM_BIRD_TWEET               GM_PROGRAM_BIRD_TWEET            ROLAND_CM32P_E_ORGAN_6   
GM_PROGRAM_TELEPHONE_RING           GM_PROGRAM_TELEPHONE_RING        ROLAND_CM32P_SLAP_3      
GM_PROGRAM_HELICOPTER               GM_PROGRAM_HELICOPTER            ROLAND_CM32P_SLAP_10     
GM_PROGRAM_APPLAUSE                 GM_PROGRAM_APPLAUSE              ROLAND_CM32P_TP_TRB_5    
GM_PROGRAM_GUNSHOT                  GM_PROGRAM_GUNSHOT               ROLAND_CM32P_E_ORGAN_6   
"""

ps = []
cm = set()

for s in mapping.strip().split("\n"):
    m = re.split("[ ]+", s.strip())
    if len(m) == 3:
        p = eval(m[1])
    else:
        assert len(m) == 4 and m[1] == "CM"
        p = eval(m[3])
        cm.add(p)
    ps.append(p)

assert len(ps) == 128

for i in range(8):
    print(f"        /* {i:1d}_ */ ", end = "")
    for j in range(16):
        p = ps[i * 16 + j]
        print(f" 0x{p:02X},", end = "")
    print()

print()

for i in range(8):
    print(f"        /* {i:1d}_ */ ", end = "")
    for j in range(16):
        p = ps[i * 16 + j]
        print(f" 0x{hi[p]:02X}," if p in cm else " 0x00,", end = "")
    print()

print()

for i in range(8):
    print(f"        /* {i:1d}_ */ ", end = "")
    for j in range(16):
        p = ps[i * 16 + j]
        print(f" 0x{lo[p]:02X}," if p in cm else " 0x08,", end = "")
    print()

