#!/usr/bin/python3

mapping = """
GM_PROGRAM_ACOUSTIC_GRAND_PIANO   ROLAND_GR09_TONE_ACOUSTIC_PIANO1
GM_PROGRAM_BRIGHT_ACOUSTIC_PIANO  ROLAND_GR09_TONE_ACOUSTIC_PIANO2
GM_PROGRAM_ELECTRIC_GRAND_PIANO   ROLAND_GR09_TONE_ELECTRIC_GRAND
GM_PROGRAM_HONKY_TONK_PIANO       ROLAND_GR09_TONE_HONKY_TONK
GM_PROGRAM_ELECTRIC_PIANO_1       ROLAND_GR09_TONE_ELECTRIC_PIANO1
GM_PROGRAM_ELECTRIC_PIANO_2       ROLAND_GR09_TONE_ELECTRIC_PIANO2
GM_PROGRAM_HARPSICHORD            ROLAND_GR09_TONE_WIRE_STRING
GM_PROGRAM_CLAVI                  ROLAND_GR09_TONE_CLAV2              
GM_PROGRAM_CELESTA                ROLAND_GR09_TONE_SPARKLE_BELL
GM_PROGRAM_GLOCKENSPIEL           ROLAND_GR09_TONE_VIBES2
GM_PROGRAM_MUSIC_BOX              ROLAND_GR09_TONE_FANTA_PAD
GM_PROGRAM_VIBRAPHONE             ROLAND_GR09_TONE_VIBES       
GM_PROGRAM_MARIMBA                ROLAND_GR09_TONE_MARIMBA
GM_PROGRAM_XYLOPHONE              ROLAND_GR09_TONE_SYNTH_BELL
GM_PROGRAM_TUBULAR_BELLS          ROLAND_GR09_TONE_HARP_PAD
GM_PROGRAM_DULCIMER               ROLAND_GR09_TONE_GUITAR_CLAV        
GM_PROGRAM_DRAWBAR_ORGAN          ROLAND_GR09_TONE_ORGAN1
GM_PROGRAM_PERCUSSIVE_ORGAN       ROLAND_GR09_TONE_ORGAN2
GM_PROGRAM_ROCK_ORGAN             ROLAND_GR09_TONE_ROCK_ORGAN1
GM_PROGRAM_CHURCH_ORGAN           ROLAND_GR09_TONE_PIPE_ORGAN1
GM_PROGRAM_REED_ORGAN             ROLAND_GR09_TONE_OMINOUS
GM_PROGRAM_ACCORDION              ROLAND_GR09_TONE_SYNTH_HARM
GM_PROGRAM_HARMONICA              ROLAND_GR09_TONE_HARMONICA
GM_PROGRAM_TANGO_ACCORDION        ROLAND_GR09_TONE_SYNTH_HARM
GM_PROGRAM_ACOUSTIC_GUITAR_NYLON  ROLAND_GR09_TONE_NYLN_GUITAR
GM_PROGRAM_ACOUSTIC_GUITAR_STEEL  ROLAND_GR09_TONE_STEEL_GUITAR1
GM_PROGRAM_ELECTRIC_GUITAR_JAZZ   ROLAND_GR09_TONE_FRETLESS_BASS
GM_PROGRAM_ELECTRIC_GUITAR_CLEAN  ROLAND_GR09_TONE_SLAP_BASS1
GM_PROGRAM_ELECTRIC_GUITAR_MUTED  ROLAND_GR09_TONE_SLAP_BASS2
GM_PROGRAM_OVERDRIVEN_GUITAR      ROLAND_GR09_TONE_FEED_BACK1
GM_PROGRAM_DISTORTION_GUITAR      ROLAND_GR09_TONE_DISTORTION_GTR2
GM_PROGRAM_GUITAR_HARMONICS       ROLAND_GR09_TONE_GTR_HARMONICS1
GM_PROGRAM_ACOUSTIC_BASS          ROLAND_GR09_TONE_ACOUSTIC_BASS1
GM_PROGRAM_ELECTRIC_BASS_FINGER   ROLAND_GR09_TONE_ELECTRIC_BASS1
GM_PROGRAM_ELECTRIC_BASS_PICK     ROLAND_GR09_TONE_PICK_BASS4
GM_PROGRAM_FRETLESS_BASS          ROLAND_GR09_TONE_FRETLESS_BASS
GM_PROGRAM_SLAP_BASS_1            ROLAND_GR09_TONE_SLAP_BASS1
GM_PROGRAM_SLAP_BASS_2            ROLAND_GR09_TONE_SLAP_BASS2   
GM_PROGRAM_SYNTH_BASS_1           ROLAND_GR09_TONE_MINI_BASS2
GM_PROGRAM_SYNTH_BASS_2           ROLAND_GR09_TONE_RESO_BASS1
GM_PROGRAM_VIOLIN                 ROLAND_GR09_TONE_VIOLIN
GM_PROGRAM_VIOLA                  ROLAND_GR09_TONE_VIOLIN
GM_PROGRAM_CELLO                  ROLAND_GR09_TONE_CELLO1
GM_PROGRAM_CONTRABASS             ROLAND_GR09_TONE_CONTRA_BASS
GM_PROGRAM_TREMOLO_STRINGS        ROLAND_GR09_TONE_CHEESO
GM_PROGRAM_PIZZICATO_STRINGS      ROLAND_GR09_TONE_OCT_BASS2
GM_PROGRAM_ORCHESTRAL_HARP        ROLAND_GR09_TONE_HARP
GM_PROGRAM_TIMPANI                ROLAND_GR09_TONE_ACOUSTIC_BASS2
GM_PROGRAM_STRING_ENSEMBLE_1      ROLAND_GR09_TONE_OCT_STRINGS      
GM_PROGRAM_STRING_ENSEMBLE_2      ROLAND_GR09_TONE_FAST_STRINGS
GM_PROGRAM_SYNTHSTRINGS_1         ROLAND_GR09_TONE_PEDAL_BASS
GM_PROGRAM_SYNTHSTRINGS_2         ROLAND_GR09_TONE_BOWED_STRINGS
GM_PROGRAM_CHOIR_AAHS             ROLAND_GR09_TONE_SYNTH_VOX1
GM_PROGRAM_VOICE_OOHS             ROLAND_GR09_TONE_SYNTH_VOX2
GM_PROGRAM_SYNTH_VOICE            ROLAND_GR09_TONE_DIGITAL_VOX1
GM_PROGRAM_ORCHESTRA_HIT          ROLAND_GR09_TONE_OCT_BRASS
GM_PROGRAM_TRUMPET                ROLAND_GR09_TONE_TRUMPET   
GM_PROGRAM_TROMBONE               ROLAND_GR09_TONE_TROMBONE
GM_PROGRAM_TUBA                   ROLAND_GR09_TONE_TUBA
GM_PROGRAM_MUTED_TRUMPET          ROLAND_GR09_TONE_MUTE_TRUMPET     
GM_PROGRAM_FRENCH_HORN            ROLAND_GR09_TONE_FRENCH_HORN      
GM_PROGRAM_BRASS_SECTION          ROLAND_GR09_TONE_BRASS_SECTION
GM_PROGRAM_SYNTHBRASS_1           ROLAND_GR09_TONE_SYNTH_BRASS1
GM_PROGRAM_SYNTHBRASS_2           ROLAND_GR09_TONE_SYNTH_BRASS3
GM_PROGRAM_SOPRANO_SAX            ROLAND_GR09_TONE_SOPRANO_SAX
GM_PROGRAM_ALTO_SAX               ROLAND_GR09_TONE_ALTO_SAX  
GM_PROGRAM_TENOR_SAX              ROLAND_GR09_TONE_TENOR_SAX
GM_PROGRAM_BARITONE_SAX           ROLAND_GR09_TONE_TENOR_SAX
GM_PROGRAM_OBOE                   ROLAND_GR09_TONE_OBOE
GM_PROGRAM_ENGLISH_HORN           ROLAND_GR09_TONE_FLUGEL_HORN
GM_PROGRAM_BASSOON                ROLAND_GR09_TONE_TP_PLUS_TB
GM_PROGRAM_CLARINET               ROLAND_GR09_TONE_CLARINET
GM_PROGRAM_PICCOLO                ROLAND_GR09_TONE_PICCOLO
GM_PROGRAM_FLUTE                  ROLAND_GR09_TONE_FLUTE   
GM_PROGRAM_RECORDER               ROLAND_GR09_TONE_PICCOLO
GM_PROGRAM_PAN_FLUTE              ROLAND_GR09_TONE_CHIFF_FLUTE
GM_PROGRAM_BLOWN_BOTTLE           ROLAND_GR09_TONE_BOTTLE_BLOW     
GM_PROGRAM_SHAKUHACHI             ROLAND_GR09_TONE_BLOW_PIPE
GM_PROGRAM_WHISTLE                ROLAND_GR09_TONE_WHISTLE
GM_PROGRAM_OCARINA                ROLAND_GR09_TONE_OCARINA
GM_PROGRAM_LEAD_1_SQUARE          ROLAND_GR09_TONE_SQUARE_LEAD
GM_PROGRAM_LEAD_2_SAWTOOTH        ROLAND_GR09_TONE_GR300_LEAD
GM_PROGRAM_LEAD_3_CALLIOPE        ROLAND_GR09_TONE_CALLIOPE
GM_PROGRAM_LEAD_4_CHIFF           ROLAND_GR09_TONE_CHIFF_PAD
GM_PROGRAM_LEAD_5_CHARANG         ROLAND_GR09_TONE_RESO_BASS1
GM_PROGRAM_LEAD_6_VOICE           ROLAND_GR09_TONE_VOX_LEAD1
GM_PROGRAM_LEAD_7_FIFTHS          ROLAND_GR09_TONE_5TH_LEAD1
GM_PROGRAM_LEAD_8_BASS_LEAD       ROLAND_GR09_TONE_OCT_BASS1      
GM_PROGRAM_PAD_1_NEW_AGE          ROLAND_GR09_TONE_HAUNT_VOX
GM_PROGRAM_PAD_2_WARM             ROLAND_GR09_TONE_SOFT_PAD
GM_PROGRAM_PAD_3_POLYSYNTH        ROLAND_GR09_TONE_POLY_SYNTH1
GM_PROGRAM_PAD_4_CHOIR            ROLAND_GR09_TONE_CHOIR_PAD
GM_PROGRAM_PAD_5_BOWED            ROLAND_GR09_TONE_PEDAL_BASS
GM_PROGRAM_PAD_6_METALLIC         ROLAND_GR09_TONE_METAL_PAD1
GM_PROGRAM_PAD_7_HALO             ROLAND_GR09_TONE_HELLOW_PAD
GM_PROGRAM_PAD_8_SWEEP            ROLAND_GR09_TONE_SWEEP_PAD1 
GM_PROGRAM_FX_1_RAIN              ROLAND_GR09_TONE_INVERSION
GM_PROGRAM_FX_2_SOUNDTRACK        ROLAND_GR09_TONE_SOUNDTRACK
GM_PROGRAM_FX_3_CRYSTAL           ROLAND_GR09_TONE_PEDAL_STEEL
GM_PROGRAM_FX_4_ATMOSPHERE        ROLAND_GR09_TONE_ATMOSPHERE     
GM_PROGRAM_FX_5_BRIGHTNESS        ROLAND_GR09_TONE_SAW_PAD
GM_PROGRAM_FX_6_GOBLINS           ROLAND_GR09_TONE_WHISPER
GM_PROGRAM_FX_7_ECHOES            ROLAND_GR09_TONE_ECHO_VOX
GM_PROGRAM_FX_8_SCI_FI            ROLAND_GR09_TONE_DIGITAL_BOW
GM_PROGRAM_SITAR                  ROLAND_GR09_TONE_ELECTRIC_SITAR1
GM_PROGRAM_BANJO                  ROLAND_GR09_TONE_BANJO           
GM_PROGRAM_SHAMISEN               ROLAND_GR09_TONE_WIRE_STRING
GM_PROGRAM_KOTO                   ROLAND_GR09_TONE_ELECTRIC_SITAR2
GM_PROGRAM_KALIMBA                ROLAND_GR09_TONE_PLUCK_DOO
GM_PROGRAM_BAG_PIPE               ROLAND_GR09_TONE_HARMONICA
GM_PROGRAM_FIDDLE                 ROLAND_GR09_TONE_FIDDLE
GM_PROGRAM_SHANAI                 ROLAND_GR09_TONE_MUTE_TRUMPET
GM_PROGRAM_TINKLE_BELL            ROLAND_GR09_TONE_TINKLE_BELL
GM_PROGRAM_AGOGO                  ROLAND_GR09_TONE_SYNTH_BELL
GM_PROGRAM_STEEL_DRUMS            ROLAND_GR09_TONE_STEEL_DRUM     
GM_PROGRAM_WOODBLOCK              ROLAND_GR09_TONE_TWEETY
GM_PROGRAM_TAIKO_DRUM             ROLAND_GR09_TONE_POP_E_PIANO
GM_PROGRAM_MELODIC_TOM            ROLAND_GR09_TONE_HARP_PAD
GM_PROGRAM_SYNTH_DRUM             ROLAND_GR09_TONE_SYNTH_BELL
GM_PROGRAM_REVERSE_CYMBAL         ROLAND_GR09_TONE_INVERSION
GM_PROGRAM_GUITAR_FRET_NOISE      ROLAND_GR09_TONE_GTR_HARMONICS2
GM_PROGRAM_BREATH_NOISE           ROLAND_GR09_TONE_BREATH
GM_PROGRAM_SEASHORE               ROLAND_GR09_TONE_INVERSION
GM_PROGRAM_BIRD_TWEET             ROLAND_GR09_TONE_MUTE_TRUMPET
GM_PROGRAM_TELEPHONE_RING         ROLAND_GR09_TONE_BRASS_BLUST
GM_PROGRAM_HELICOPTER             ROLAND_GR09_TONE_ALTO_GROWL
GM_PROGRAM_APPLAUSE               ROLAND_GR09_TONE_INVERSION
GM_PROGRAM_GUNSHOT                ROLAND_GR09_TONE_DOUBLE_SCAT
"""

ROLAND_GR09_TONE_ACOUSTIC_PIANO1     = 0x00
ROLAND_GR09_TONE_ACOUSTIC_PIANO2     = 0x01
ROLAND_GR09_TONE_HONKY_TONK          = 0x02
ROLAND_GR09_TONE_ELECTRIC_PIANO1     = 0x03
ROLAND_GR09_TONE_ELECTRIC_PIANO2     = 0x04
ROLAND_GR09_TONE_ELECTRIC_GRAND      = 0x05
ROLAND_GR09_TONE_POP_E_PIANO         = 0x06
ROLAND_GR09_TONE_RHODES              = 0x07
ROLAND_GR09_TONE_OVER_TONE           = 0x08
ROLAND_GR09_TONE_A_PIANO_PLUS_VIB    = 0x09
ROLAND_GR09_TONE_A_PIANO_PLUS_VOX    = 0x0A
ROLAND_GR09_TONE_CLAV1               = 0x0B
ROLAND_GR09_TONE_CLAV2               = 0x0C
ROLAND_GR09_TONE_VIBES               = 0x0D
ROLAND_GR09_TONE_VIBES2              = 0x0E
ROLAND_GR09_TONE_MARIMBA             = 0x0F
ROLAND_GR09_TONE_ORGAN1              = 0x10
ROLAND_GR09_TONE_ORGAN2              = 0x11
ROLAND_GR09_TONE_ROCK_ORGAN1         = 0x12
ROLAND_GR09_TONE_JAZZ_ORGAN1         = 0x13
ROLAND_GR09_TONE_JAZZ_ORGAN2         = 0x14
ROLAND_GR09_TONE_CHEESO              = 0x15
ROLAND_GR09_TONE_PIPE_ORGAN1         = 0x16
ROLAND_GR09_TONE_STEEL_GUITAR1       = 0x17
ROLAND_GR09_TONE_NYLN_GUITAR         = 0x18
ROLAND_GR09_TONE_12STR_GUITAR        = 0x19
ROLAND_GR09_TONE_GTR_HARMONICS1      = 0x1A
ROLAND_GR09_TONE_GTR_HARMONICS2      = 0x1B
ROLAND_GR09_TONE_DISTORTION_GTR1     = 0x1C
ROLAND_GR09_TONE_DISTORTION_GTR2     = 0x1D
ROLAND_GR09_TONE_GUITAR_CLAV         = 0x1E
ROLAND_GR09_TONE_GUITAR_LEAD         = 0x1F
ROLAND_GR09_TONE_FEED_BACK1          = 0x20
ROLAND_GR09_TONE_FEED_BACK2          = 0x21
ROLAND_GR09_TONE_ONLY_FEEDBACK       = 0x22
ROLAND_GR09_TONE_PEDAL_STEEL         = 0x23
ROLAND_GR09_TONE_BANJO               = 0x24
ROLAND_GR09_TONE_ELECTRIC_SITAR1     = 0x25
ROLAND_GR09_TONE_ELECTRIC_SITAR2     = 0x26
ROLAND_GR09_TONE_ACOUSTIC_BASS1      = 0x27
ROLAND_GR09_TONE_ACOUSTIC_BASS2      = 0x28
ROLAND_GR09_TONE_ELECTRIC_BASS1      = 0x29
ROLAND_GR09_TONE_PICK_BASS1          = 0x2A
ROLAND_GR09_TONE_PICK_BASS2          = 0x2B
ROLAND_GR09_TONE_PICK_BASS3          = 0x2C
ROLAND_GR09_TONE_PICK_BASS4          = 0x2D
ROLAND_GR09_TONE_SLAP_BASS1          = 0x2E
ROLAND_GR09_TONE_SLAP_BASS2          = 0x2F
ROLAND_GR09_TONE_DETUNED_SLAP        = 0x30
ROLAND_GR09_TONE_FRETLESS_BASS       = 0x31
ROLAND_GR09_TONE_FRETLESS_BASS2      = 0x32
ROLAND_GR09_TONE_MINI_BASS1          = 0x33
ROLAND_GR09_TONE_MINI_BASS2          = 0x34
ROLAND_GR09_TONE_OCT_BASS1           = 0x35
ROLAND_GR09_TONE_OCT_BASS2           = 0x36
ROLAND_GR09_TONE_RESO_BASS1          = 0x37
ROLAND_GR09_TONE_PEDAL_BASS          = 0x38
ROLAND_GR09_TONE_FAST_STRINGS        = 0x39
ROLAND_GR09_TONE_SLOW_STRINGS        = 0x3A
ROLAND_GR09_TONE_OCT_STRINGS         = 0x3B
ROLAND_GR09_TONE_BOWED_STRINGS       = 0x3C
ROLAND_GR09_TONE_BRIGHT_STRINGS1     = 0x3D
ROLAND_GR09_TONE_DARK_STRINGS        = 0x3E
ROLAND_GR09_TONE_JP_STRINGS          = 0x3F
ROLAND_GR09_TONE_JP_PAD1             = 0x40
ROLAND_GR09_TONE_OCT_JP_STRINGS      = 0x41
ROLAND_GR09_TONE_JP_STRINGS2         = 0x42
ROLAND_GR09_TONE_HYBRID_STRINGS      = 0x43
ROLAND_GR09_TONE_HYBRID_STRINGS2     = 0x44
ROLAND_GR09_TONE_HYBRID_STRINGS3     = 0x45
ROLAND_GR09_TONE_VIOLIN              = 0x46
ROLAND_GR09_TONE_CELLO1              = 0x47
ROLAND_GR09_TONE_CONTRA_BASS         = 0x48
ROLAND_GR09_TONE_FIDDLE              = 0x49
ROLAND_GR09_TONE_WIRE_STRING         = 0x4A
ROLAND_GR09_TONE_HARP                = 0x4B
ROLAND_GR09_TONE_SYNTH_HARP          = 0x4C
ROLAND_GR09_TONE_SYNTH_VOX1          = 0x4D
ROLAND_GR09_TONE_SYNTH_VOX2          = 0x4E
ROLAND_GR09_TONE_DOUBLE_VOX          = 0x4F
ROLAND_GR09_TONE_VOX_LEAD1           = 0x50
ROLAND_GR09_TONE_HAUNT_VOX           = 0x51
ROLAND_GR09_TONE_CHIFF_PAD           = 0x52
ROLAND_GR09_TONE_BREATH              = 0x53
ROLAND_GR09_TONE_WIND_VOX            = 0x54
ROLAND_GR09_TONE_INVERSION           = 0x55
ROLAND_GR09_TONE_SYNTH_HARM          = 0x56
ROLAND_GR09_TONE_ECHO_VOX            = 0x57
ROLAND_GR09_TONE_SCAT_VOX            = 0x58
ROLAND_GR09_TONE_DOUBLE_SCAT         = 0x59
ROLAND_GR09_TONE_NYLON_SCAT          = 0x5A
ROLAND_GR09_TONE_PLUCK_DOO           = 0x5B
ROLAND_GR09_TONE_BRASS_SECTION       = 0x5C
ROLAND_GR09_TONE_BRASS_SECTION2      = 0x5D
ROLAND_GR09_TONE_BRASS_SECTION3      = 0x5E
ROLAND_GR09_TONE_OCT_BRASS           = 0x5F
ROLAND_GR09_TONE_SYNTH_BRASS1        = 0x60
ROLAND_GR09_TONE_SYNTH_BRASS2        = 0x61
ROLAND_GR09_TONE_SYNTH_BRASS3        = 0x62
ROLAND_GR09_TONE_BRASS_BLUST         = 0x63
ROLAND_GR09_TONE_RICH_BRASS          = 0x64
ROLAND_GR09_TONE_TRUMPET             = 0x65
ROLAND_GR09_TONE_TROMBONE            = 0x66
ROLAND_GR09_TONE_TUBA                = 0x67
ROLAND_GR09_TONE_BRIGHT_TRUMPET      = 0x68
ROLAND_GR09_TONE_MUTE_TRUMPET        = 0x69
ROLAND_GR09_TONE_ALTO_SAX_PLUS_TP    = 0x6A
ROLAND_GR09_TONE_TP_PLUS_TB          = 0x6B
ROLAND_GR09_TONE_TROMBONE_PLUS_SAX   = 0x6C
ROLAND_GR09_TONE_FRENCH_HORN         = 0x6D
ROLAND_GR09_TONE_FLUGEL_HORN         = 0x6E
ROLAND_GR09_TONE_DETUNED_HORN        = 0x6F
ROLAND_GR09_TONE_VELOCITY_HORN       = 0x70
ROLAND_GR09_TONE_DUAL_HORN           = 0x71
ROLAND_GR09_TONE_PULSE_HORN          = 0x72
ROLAND_GR09_TONE_SYNTH_HOM           = 0x73
ROLAND_GR09_TONE_BREATHY_HORN        = 0x74
ROLAND_GR09_TONE_FLUGEL_PLUS_TRUMPET = 0x75
ROLAND_GR09_TONE_FLUGEL_PLUS_FLUTE   = 0x76
ROLAND_GR09_TONE_ALTO_SAX            = 0x77
ROLAND_GR09_TONE_TENOR_SAX           = 0x78
ROLAND_GR09_TONE_SOPRANO_SAX         = 0x79
ROLAND_GR09_TONE_ALTO_GROWL          = 0x7A
ROLAND_GR09_TONE_TENOR_GROWL         = 0x7B
ROLAND_GR09_TONE_ALTO_TENOR          = 0x7C
ROLAND_GR09_TONE_PICCOLO             = 0x7D
ROLAND_GR09_TONE_FLUTE               = 0x7E
ROLAND_GR09_TONE_OBOE                = 0x7F
ROLAND_GR09_TONE_CLARINET            = 0x80
ROLAND_GR09_TONE_CHIFF_FLUTE         = 0x81
ROLAND_GR09_TONE_MUTE_TP_PLUS_FLUTE  = 0x82
ROLAND_GR09_TONE_VIBE_PLUS_FLUTE     = 0x83
ROLAND_GR09_TONE_OCARINA             = 0x84
ROLAND_GR09_TONE_CALLIOPE            = 0x85
ROLAND_GR09_TONE_BOTTLE_BLOW         = 0x86
ROLAND_GR09_TONE_BLOW_PIPE           = 0x87
ROLAND_GR09_TONE_HARMONICA           = 0x88
ROLAND_GR09_TONE_WHISTLE             = 0x89
ROLAND_GR09_TONE_GR300_LEAD          = 0x8A
ROLAND_GR09_TONE_PLAIN_LEAD          = 0x8B
ROLAND_GR09_TONE_POLY_SYNTH1         = 0x8C
ROLAND_GR09_TONE_TWEETY              = 0x8D
ROLAND_GR09_TONE_SOFT_PAD            = 0x8E
ROLAND_GR09_TONE_METAL_PAD1          = 0x8F
ROLAND_GR09_TONE_SQUARE_LEAD         = 0x90
ROLAND_GR09_TONE_SYNTH_LEAD          = 0x91
ROLAND_GR09_TONE_SYNTH_LEAD2         = 0x92
ROLAND_GR09_TONE_SYNTH_LEAD3         = 0x93
ROLAND_GR09_TONE_SYNTH_LEAD4         = 0x94
ROLAND_GR09_TONE_SYNTH_LEAD5         = 0x95
ROLAND_GR09_TONE_5TH_LEAD1           = 0x96
ROLAND_GR09_TONE_SAW_LEAD            = 0x97
ROLAND_GR09_TONE_FAT_LEAD            = 0x98
ROLAND_GR09_TONE_SAW_PAD             = 0x99
ROLAND_GR09_TONE_PULSE_PAD           = 0x9A
ROLAND_GR09_TONE_TECHNO              = 0x9B
ROLAND_GR09_TONE_OMINOUS             = 0x9C
ROLAND_GR09_TONE_HARP_PAD            = 0x9D
ROLAND_GR09_TONE_INVISIBLE           = 0x9E
ROLAND_GR09_TONE_ATMOSPHERE          = 0x9F
ROLAND_GR09_TONE_DIGITAL_PLUCK       = 0xA0
ROLAND_GR09_TONE_PLUCK_SWEEP1        = 0xA1
ROLAND_GR09_TONE_PLUCK_SWEEP2        = 0xA2
ROLAND_GR09_TONE_SWEEP_PAD1          = 0xA3
ROLAND_GR09_TONE_OCTAVE_PAD1         = 0xA4
ROLAND_GR09_TONE_HELLOW_PAD          = 0xA5
ROLAND_GR09_TONE_CHOIR_PAD           = 0xA6
ROLAND_GR09_TONE_DIGITAL_BOW         = 0xA7
ROLAND_GR09_TONE_DIGITAL_VOX1        = 0xA8
ROLAND_GR09_TONE_SOUNDTRACK          = 0xA9
ROLAND_GR09_TONE_BOWED_GLASS         = 0xAA
ROLAND_GR09_TONE_HEAVEN              = 0xAB
ROLAND_GR09_TONE_FANTA_BELL          = 0xAC
ROLAND_GR09_TONE_TINKLE_BELL         = 0xAD
ROLAND_GR09_TONE_SYNTH_BELL          = 0xAE
ROLAND_GR09_TONE_SPARKLE_BELL        = 0xAF
ROLAND_GR09_TONE_FANTASIA            = 0xB0
ROLAND_GR09_TONE_FANTA_PAD           = 0xB1
ROLAND_GR09_TONE_WHISPER             = 0xB2
ROLAND_GR09_TONE_STEEL_DRUM          = 0xB3

msb = [0] * 128
lsb = [0] * 128

for i, s in enumerate(mapping.strip().split("\n")):
    gm, rl = s.strip().split(" ", 1)
    rl = rl.lstrip()
    assert(gm.startswith("GM_PROGRAM_"))
    assert(rl.startswith("ROLAND_GR09_TONE_"))
    tone = eval(rl)
    msb[i] = tone >> 7
    lsb[i] = tone & 0x7F

for i in range(8):
    print("        /*      {0:X}_ */ ".format(i), end = "")
    for j in range(0, 16, 2):
        print(" 0x{0:X}{1:X},".format(msb[i * 16 + j], msb[i * 16 + j + 1]), end = "")
    print()
    
for i in range(8):
    print("        /*      {0:X}_ */ ".format(i), end = "")
    for j in range(0, 16):
        print(" 0x{0:02X},".format(lsb[i * 16 + j]), end = "")
    print()
